/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  HTTPValidationError,
  ProfileData,
  ProfileDraftRequest,
  ProfileDraftResponse,
  ProfileResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * @summary Get Profile
 */
export const useGetProfileApiTeamsTeamIdProfileGetHook = () => {
        const getProfileApiTeamsTeamIdProfileGet = useCustomInstance<ProfileResponse>();

        return useCallback((
    teamId: string,
 signal?: AbortSignal
) => {
        return getProfileApiTeamsTeamIdProfileGet(
          {url: `/api/teams/${teamId}/profile`, method: 'GET', signal
    },
          );
        }, [getProfileApiTeamsTeamIdProfileGet])
      }




export const getGetProfileApiTeamsTeamIdProfileGetInfiniteQueryKey = (teamId: string,) => {
    return [
    'infinite', `/api/teams/${teamId}/profile`
    ] as const;
    }

export const getGetProfileApiTeamsTeamIdProfileGetQueryKey = (teamId: string,) => {
    return [
    `/api/teams/${teamId}/profile`
    ] as const;
    }


export const useGetProfileApiTeamsTeamIdProfileGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProfileApiTeamsTeamIdProfileGetInfiniteQueryKey(teamId);

  const getProfileApiTeamsTeamIdProfileGet =  useGetProfileApiTeamsTeamIdProfileGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>> = ({ signal }) => getProfileApiTeamsTeamIdProfileGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProfileApiTeamsTeamIdProfileGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>>
export type GetProfileApiTeamsTeamIdProfileGetInfiniteQueryError = HTTPValidationError


export function useGetProfileApiTeamsTeamIdProfileGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfileApiTeamsTeamIdProfileGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfileApiTeamsTeamIdProfileGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Profile
 */

export function useGetProfileApiTeamsTeamIdProfileGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetProfileApiTeamsTeamIdProfileGetInfiniteQueryOptions(teamId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetProfileApiTeamsTeamIdProfileGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProfileApiTeamsTeamIdProfileGetQueryKey(teamId);

  const getProfileApiTeamsTeamIdProfileGet =  useGetProfileApiTeamsTeamIdProfileGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>> = ({ signal }) => getProfileApiTeamsTeamIdProfileGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProfileApiTeamsTeamIdProfileGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>>
export type GetProfileApiTeamsTeamIdProfileGetQueryError = HTTPValidationError


export function useGetProfileApiTeamsTeamIdProfileGet<TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfileApiTeamsTeamIdProfileGet<TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfileApiTeamsTeamIdProfileGet<TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Profile
 */

export function useGetProfileApiTeamsTeamIdProfileGet<TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetProfileApiTeamsTeamIdProfileGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetProfileApiTeamsTeamIdProfileGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProfileApiTeamsTeamIdProfileGetQueryKey(teamId);

  const getProfileApiTeamsTeamIdProfileGet =  useGetProfileApiTeamsTeamIdProfileGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>> = ({ signal }) => getProfileApiTeamsTeamIdProfileGet(teamId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProfileApiTeamsTeamIdProfileGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>>
export type GetProfileApiTeamsTeamIdProfileGetSuspenseQueryError = HTTPValidationError


export function useGetProfileApiTeamsTeamIdProfileGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfileApiTeamsTeamIdProfileGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfileApiTeamsTeamIdProfileGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Profile
 */

export function useGetProfileApiTeamsTeamIdProfileGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetProfileApiTeamsTeamIdProfileGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetProfileApiTeamsTeamIdProfileGetSuspenseQueryOptions(teamId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Put Profile
 */
export const usePutProfileApiTeamsTeamIdProfilePutHook = () => {
        const putProfileApiTeamsTeamIdProfilePut = useCustomInstance<ProfileResponse>();

        return useCallback((
    teamId: string,
    profileData: ProfileData,
 signal?: AbortSignal
) => {
        return putProfileApiTeamsTeamIdProfilePut(
          {url: `/api/teams/${teamId}/profile`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: profileData, signal
    },
          );
        }, [putProfileApiTeamsTeamIdProfilePut])
      }



export const usePutProfileApiTeamsTeamIdProfilePutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePutProfileApiTeamsTeamIdProfilePutHook>>>, TError,{teamId: string;data: ProfileData}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePutProfileApiTeamsTeamIdProfilePutHook>>>, TError,{teamId: string;data: ProfileData}, TContext> => {

const mutationKey = ['putProfileApiTeamsTeamIdProfilePut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const putProfileApiTeamsTeamIdProfilePut =  usePutProfileApiTeamsTeamIdProfilePutHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof usePutProfileApiTeamsTeamIdProfilePutHook>>>, {teamId: string;data: ProfileData}> = (props) => {
          const {teamId,data} = props ?? {};

          return  putProfileApiTeamsTeamIdProfilePut(teamId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutProfileApiTeamsTeamIdProfilePutMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof usePutProfileApiTeamsTeamIdProfilePutHook>>>>
    export type PutProfileApiTeamsTeamIdProfilePutMutationBody = ProfileData
    export type PutProfileApiTeamsTeamIdProfilePutMutationError = HTTPValidationError

    /**
 * @summary Put Profile
 */
export const usePutProfileApiTeamsTeamIdProfilePut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePutProfileApiTeamsTeamIdProfilePutHook>>>, TError,{teamId: string;data: ProfileData}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof usePutProfileApiTeamsTeamIdProfilePutHook>>>,
        TError,
        {teamId: string;data: ProfileData},
        TContext
      > => {
      return useMutation(usePutProfileApiTeamsTeamIdProfilePutMutationOptions(options), queryClient);
    }
    /**
 * @summary Draft Profile From Document
 */
export const useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHook = () => {
        const draftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPost = useCustomInstance<ProfileDraftResponse>();

        return useCallback((
    teamId: string,
    profileDraftRequest: ProfileDraftRequest,
 signal?: AbortSignal
) => {
        return draftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPost(
          {url: `/api/teams/${teamId}/profile/draft-from-document`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: profileDraftRequest, signal
    },
          );
        }, [draftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPost])
      }



export const useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHook>>>, TError,{teamId: string;data: ProfileDraftRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHook>>>, TError,{teamId: string;data: ProfileDraftRequest}, TContext> => {

const mutationKey = ['draftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const draftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPost =  useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHook>>>, {teamId: string;data: ProfileDraftRequest}> = (props) => {
          const {teamId,data} = props ?? {};

          return  draftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPost(teamId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHook>>>>
    export type DraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostMutationBody = ProfileDraftRequest
    export type DraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostMutationError = HTTPValidationError

    /**
 * @summary Draft Profile From Document
 */
export const useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHook>>>, TError,{teamId: string;data: ProfileDraftRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHook>>>,
        TError,
        {teamId: string;data: ProfileDraftRequest},
        TContext
      > => {
      return useMutation(useDraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostMutationOptions(options), queryClient);
    }
