/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Suggestions
 */
export const ListSuggestionsApiTeamsTeamIdSuggestionsGetParams = zod.object({
  "team_id": zod.uuid()
})

export const ListSuggestionsApiTeamsTeamIdSuggestionsGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListSuggestionsApiTeamsTeamIdSuggestionsGetResponseItem = zod.object({
  "id": zod.string(),
  "post_id": zod.string(),
  "package_id": zod.string(),
  "proposer_team_id": zod.string(),
  "target_team_id": zod.string(),
  "original_text": zod.string(),
  "adapted_preview": zod.union([zod.string(),zod.null()]).optional(),
  "proposed_text": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.string(),
  "response": zod.union([zod.string(),zod.null()]).optional(),
  "response_reason": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_id": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_version": zod.union([zod.number(),zod.null()]).optional(),
  "suggestion_type": zod.union([zod.enum(['edit_text', 'add_detail', 'flag_incorrect', 'request_clarification', 'propose_alternative']),zod.null()]).optional(),
  "approved_team_ids": zod.array(zod.string()).optional(),
  "awaiting_team_ids": zod.array(zod.string()).optional(),
  "applied_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const ListSuggestionsApiTeamsTeamIdSuggestionsGetResponse = zod.array(ListSuggestionsApiTeamsTeamIdSuggestionsGetResponseItem)

/**
 * @summary Create Suggestion
 */
export const CreateSuggestionApiPostsPostIdSuggestionsPostParams = zod.object({
  "post_id": zod.uuid()
})

export const CreateSuggestionApiPostsPostIdSuggestionsPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})


export const createSuggestionApiPostsPostIdSuggestionsPostBodySuggestionTypeDefault = `edit_text`;

export const CreateSuggestionApiPostsPostIdSuggestionsPostBody = zod.object({
  "text": zod.string().min(1),
  "target_node_id": zod.union([zod.string(),zod.null()]).optional(),
  "suggestion_type": zod.union([zod.enum(['edit_text', 'add_detail', 'flag_incorrect', 'request_clarification', 'propose_alternative']),zod.null()]).default(createSuggestionApiPostsPostIdSuggestionsPostBodySuggestionTypeDefault)
})

/**
 * @summary Respond Suggestion
 */
export const RespondSuggestionApiSuggestionsSuggestionIdRespondPostParams = zod.object({
  "suggestion_id": zod.uuid()
})

export const RespondSuggestionApiSuggestionsSuggestionIdRespondPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const RespondSuggestionApiSuggestionsSuggestionIdRespondPostBody = zod.object({
  "response": zod.enum(['accept', 'edit', 'reject']),
  "reason": zod.union([zod.string(),zod.null()]).optional(),
  "edited_text": zod.union([zod.string(),zod.null()]).optional()
})

export const RespondSuggestionApiSuggestionsSuggestionIdRespondPostResponse = zod.object({
  "id": zod.string(),
  "post_id": zod.string(),
  "package_id": zod.string(),
  "proposer_team_id": zod.string(),
  "target_team_id": zod.string(),
  "original_text": zod.string(),
  "adapted_preview": zod.union([zod.string(),zod.null()]).optional(),
  "proposed_text": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.string(),
  "response": zod.union([zod.string(),zod.null()]).optional(),
  "response_reason": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_id": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_version": zod.union([zod.number(),zod.null()]).optional(),
  "suggestion_type": zod.union([zod.enum(['edit_text', 'add_detail', 'flag_incorrect', 'request_clarification', 'propose_alternative']),zod.null()]).optional(),
  "approved_team_ids": zod.array(zod.string()).optional(),
  "awaiting_team_ids": zod.array(zod.string()).optional(),
  "applied_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * Record this team's approval; applies when both teams have approved.
 * @summary Approve Suggestion
 */
export const ApproveSuggestionApiSuggestionsSuggestionIdApprovePostParams = zod.object({
  "suggestion_id": zod.uuid()
})

export const ApproveSuggestionApiSuggestionsSuggestionIdApprovePostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ApproveSuggestionApiSuggestionsSuggestionIdApprovePostResponse = zod.object({
  "id": zod.string(),
  "post_id": zod.string(),
  "package_id": zod.string(),
  "proposer_team_id": zod.string(),
  "target_team_id": zod.string(),
  "original_text": zod.string(),
  "adapted_preview": zod.union([zod.string(),zod.null()]).optional(),
  "proposed_text": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.string(),
  "response": zod.union([zod.string(),zod.null()]).optional(),
  "response_reason": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_id": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_version": zod.union([zod.number(),zod.null()]).optional(),
  "suggestion_type": zod.union([zod.enum(['edit_text', 'add_detail', 'flag_incorrect', 'request_clarification', 'propose_alternative']),zod.null()]).optional(),
  "approved_team_ids": zod.array(zod.string()).optional(),
  "awaiting_team_ids": zod.array(zod.string()).optional(),
  "applied_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * Proposer withdraws the edit request (open or awaiting approvals only).
 * @summary Cancel Suggestion
 */
export const CancelSuggestionApiSuggestionsSuggestionIdCancelPostParams = zod.object({
  "suggestion_id": zod.uuid()
})

export const CancelSuggestionApiSuggestionsSuggestionIdCancelPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const CancelSuggestionApiSuggestionsSuggestionIdCancelPostResponse = zod.object({
  "id": zod.string(),
  "post_id": zod.string(),
  "package_id": zod.string(),
  "proposer_team_id": zod.string(),
  "target_team_id": zod.string(),
  "original_text": zod.string(),
  "adapted_preview": zod.union([zod.string(),zod.null()]).optional(),
  "proposed_text": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.string(),
  "response": zod.union([zod.string(),zod.null()]).optional(),
  "response_reason": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_id": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_version": zod.union([zod.number(),zod.null()]).optional(),
  "suggestion_type": zod.union([zod.enum(['edit_text', 'add_detail', 'flag_incorrect', 'request_clarification', 'propose_alternative']),zod.null()]).optional(),
  "approved_team_ids": zod.array(zod.string()).optional(),
  "awaiting_team_ids": zod.array(zod.string()).optional(),
  "applied_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary Close Suggestion
 */
export const CloseSuggestionApiSuggestionsSuggestionIdClosePostParams = zod.object({
  "suggestion_id": zod.uuid()
})

export const CloseSuggestionApiSuggestionsSuggestionIdClosePostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const CloseSuggestionApiSuggestionsSuggestionIdClosePostResponse = zod.object({
  "id": zod.string(),
  "post_id": zod.string(),
  "package_id": zod.string(),
  "proposer_team_id": zod.string(),
  "target_team_id": zod.string(),
  "original_text": zod.string(),
  "adapted_preview": zod.union([zod.string(),zod.null()]).optional(),
  "proposed_text": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.string(),
  "response": zod.union([zod.string(),zod.null()]).optional(),
  "response_reason": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_id": zod.union([zod.string(),zod.null()]).optional(),
  "target_node_version": zod.union([zod.number(),zod.null()]).optional(),
  "suggestion_type": zod.union([zod.enum(['edit_text', 'add_detail', 'flag_incorrect', 'request_clarification', 'propose_alternative']),zod.null()]).optional(),
  "approved_team_ids": zod.array(zod.string()).optional(),
  "awaiting_team_ids": zod.array(zod.string()).optional(),
  "applied_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary Create Review Action
 */
export const CreateReviewActionApiPostsPostIdReviewActionsPostParams = zod.object({
  "post_id": zod.uuid()
})

export const CreateReviewActionApiPostsPostIdReviewActionsPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const CreateReviewActionApiPostsPostIdReviewActionsPostBody = zod.object({
  "action": zod.enum(['agree', 'request_changes', 'blocked']),
  "note": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Create Comment
 */
export const CreateCommentApiPostsPostIdCommentsPostParams = zod.object({
  "post_id": zod.uuid()
})

export const CreateCommentApiPostsPostIdCommentsPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})




export const CreateCommentApiPostsPostIdCommentsPostBody = zod.object({
  "body": zod.string().min(1)
})

/**
 * @summary List Comments
 */
export const ListCommentsApiPostsPostIdCommentsGetParams = zod.object({
  "post_id": zod.uuid()
})

export const ListCommentsApiPostsPostIdCommentsGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListCommentsApiPostsPostIdCommentsGetResponseItem = zod.object({
  "id": zod.string(),
  "post_id": zod.string(),
  "author_team_id": zod.string(),
  "original_body": zod.string(),
  "adapted_body": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const ListCommentsApiPostsPostIdCommentsGetResponse = zod.array(ListCommentsApiPostsPostIdCommentsGetResponseItem)

