/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  DecisionResponse,
  HTTPValidationError,
  ListReviewItemsApiTeamsTeamIdReviewItemsGetParams,
  ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams,
  ProposeResolutionRequest,
  ResolveReviewRequest,
  ReviewItemResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * @summary List Review Items
 */
export const useListReviewItemsApiTeamsTeamIdReviewItemsGetHook = () => {
        const listReviewItemsApiTeamsTeamIdReviewItemsGet = useCustomInstance<ReviewItemResponse[]>();

        return useCallback((
    teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams,
 signal?: AbortSignal
) => {
        return listReviewItemsApiTeamsTeamIdReviewItemsGet(
          {url: `/api/teams/${teamId}/review-items`, method: 'GET',
        params, signal
    },
          );
        }, [listReviewItemsApiTeamsTeamIdReviewItemsGet])
      }




export const getListReviewItemsApiTeamsTeamIdReviewItemsGetInfiniteQueryKey = (teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams,) => {
    return [
    'infinite', `/api/teams/${teamId}/review-items`, ...(params ? [params] : [])
    ] as const;
    }

export const getListReviewItemsApiTeamsTeamIdReviewItemsGetQueryKey = (teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams,) => {
    return [
    `/api/teams/${teamId}/review-items`, ...(params ? [params] : [])
    ] as const;
    }


export const useListReviewItemsApiTeamsTeamIdReviewItemsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>>, TError = HTTPValidationError>(teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReviewItemsApiTeamsTeamIdReviewItemsGetInfiniteQueryKey(teamId,params);

  const listReviewItemsApiTeamsTeamIdReviewItemsGet =  useListReviewItemsApiTeamsTeamIdReviewItemsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>> = ({ signal }) => listReviewItemsApiTeamsTeamIdReviewItemsGet(teamId,params, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReviewItemsApiTeamsTeamIdReviewItemsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>>
export type ListReviewItemsApiTeamsTeamIdReviewItemsGetInfiniteQueryError = HTTPValidationError


export function useListReviewItemsApiTeamsTeamIdReviewItemsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string,
    params: undefined |  ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReviewItemsApiTeamsTeamIdReviewItemsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReviewItemsApiTeamsTeamIdReviewItemsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Review Items
 */

export function useListReviewItemsApiTeamsTeamIdReviewItemsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListReviewItemsApiTeamsTeamIdReviewItemsGetInfiniteQueryOptions(teamId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListReviewItemsApiTeamsTeamIdReviewItemsGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReviewItemsApiTeamsTeamIdReviewItemsGetQueryKey(teamId,params);

  const listReviewItemsApiTeamsTeamIdReviewItemsGet =  useListReviewItemsApiTeamsTeamIdReviewItemsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>> = ({ signal }) => listReviewItemsApiTeamsTeamIdReviewItemsGet(teamId,params, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReviewItemsApiTeamsTeamIdReviewItemsGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>>
export type ListReviewItemsApiTeamsTeamIdReviewItemsGetQueryError = HTTPValidationError


export function useListReviewItemsApiTeamsTeamIdReviewItemsGet<TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params: undefined |  ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReviewItemsApiTeamsTeamIdReviewItemsGet<TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReviewItemsApiTeamsTeamIdReviewItemsGet<TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Review Items
 */

export function useListReviewItemsApiTeamsTeamIdReviewItemsGet<TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListReviewItemsApiTeamsTeamIdReviewItemsGetQueryOptions(teamId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListReviewItemsApiTeamsTeamIdReviewItemsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReviewItemsApiTeamsTeamIdReviewItemsGetQueryKey(teamId,params);

  const listReviewItemsApiTeamsTeamIdReviewItemsGet =  useListReviewItemsApiTeamsTeamIdReviewItemsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>> = ({ signal }) => listReviewItemsApiTeamsTeamIdReviewItemsGet(teamId,params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReviewItemsApiTeamsTeamIdReviewItemsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>>
export type ListReviewItemsApiTeamsTeamIdReviewItemsGetSuspenseQueryError = HTTPValidationError


export function useListReviewItemsApiTeamsTeamIdReviewItemsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params: undefined |  ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReviewItemsApiTeamsTeamIdReviewItemsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReviewItemsApiTeamsTeamIdReviewItemsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Review Items
 */

export function useListReviewItemsApiTeamsTeamIdReviewItemsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListReviewItemsApiTeamsTeamIdReviewItemsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListReviewItemsApiTeamsTeamIdReviewItemsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListReviewItemsApiTeamsTeamIdReviewItemsGetSuspenseQueryOptions(teamId,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Propose Resolution
 */
export const useProposeResolutionApiReviewItemsItemIdProposePostHook = () => {
        const proposeResolutionApiReviewItemsItemIdProposePost = useCustomInstance<ReviewItemResponse>();

        return useCallback((
    itemId: string,
    proposeResolutionRequest: ProposeResolutionRequest,
 signal?: AbortSignal
) => {
        return proposeResolutionApiReviewItemsItemIdProposePost(
          {url: `/api/review-items/${itemId}/propose`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: proposeResolutionRequest, signal
    },
          );
        }, [proposeResolutionApiReviewItemsItemIdProposePost])
      }



export const useProposeResolutionApiReviewItemsItemIdProposePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useProposeResolutionApiReviewItemsItemIdProposePostHook>>>, TError,{itemId: string;data: ProposeResolutionRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useProposeResolutionApiReviewItemsItemIdProposePostHook>>>, TError,{itemId: string;data: ProposeResolutionRequest}, TContext> => {

const mutationKey = ['proposeResolutionApiReviewItemsItemIdProposePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const proposeResolutionApiReviewItemsItemIdProposePost =  useProposeResolutionApiReviewItemsItemIdProposePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useProposeResolutionApiReviewItemsItemIdProposePostHook>>>, {itemId: string;data: ProposeResolutionRequest}> = (props) => {
          const {itemId,data} = props ?? {};

          return  proposeResolutionApiReviewItemsItemIdProposePost(itemId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProposeResolutionApiReviewItemsItemIdProposePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useProposeResolutionApiReviewItemsItemIdProposePostHook>>>>
    export type ProposeResolutionApiReviewItemsItemIdProposePostMutationBody = ProposeResolutionRequest
    export type ProposeResolutionApiReviewItemsItemIdProposePostMutationError = HTTPValidationError

    /**
 * @summary Propose Resolution
 */
export const useProposeResolutionApiReviewItemsItemIdProposePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useProposeResolutionApiReviewItemsItemIdProposePostHook>>>, TError,{itemId: string;data: ProposeResolutionRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useProposeResolutionApiReviewItemsItemIdProposePostHook>>>,
        TError,
        {itemId: string;data: ProposeResolutionRequest},
        TContext
      > => {
      return useMutation(useProposeResolutionApiReviewItemsItemIdProposePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Resolve Review Item
 */
export const useResolveReviewItemApiReviewItemsItemIdResolvePostHook = () => {
        const resolveReviewItemApiReviewItemsItemIdResolvePost = useCustomInstance<ReviewItemResponse>();

        return useCallback((
    itemId: string,
    resolveReviewRequest: ResolveReviewRequest,
 signal?: AbortSignal
) => {
        return resolveReviewItemApiReviewItemsItemIdResolvePost(
          {url: `/api/review-items/${itemId}/resolve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resolveReviewRequest, signal
    },
          );
        }, [resolveReviewItemApiReviewItemsItemIdResolvePost])
      }



export const useResolveReviewItemApiReviewItemsItemIdResolvePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useResolveReviewItemApiReviewItemsItemIdResolvePostHook>>>, TError,{itemId: string;data: ResolveReviewRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useResolveReviewItemApiReviewItemsItemIdResolvePostHook>>>, TError,{itemId: string;data: ResolveReviewRequest}, TContext> => {

const mutationKey = ['resolveReviewItemApiReviewItemsItemIdResolvePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const resolveReviewItemApiReviewItemsItemIdResolvePost =  useResolveReviewItemApiReviewItemsItemIdResolvePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useResolveReviewItemApiReviewItemsItemIdResolvePostHook>>>, {itemId: string;data: ResolveReviewRequest}> = (props) => {
          const {itemId,data} = props ?? {};

          return  resolveReviewItemApiReviewItemsItemIdResolvePost(itemId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResolveReviewItemApiReviewItemsItemIdResolvePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useResolveReviewItemApiReviewItemsItemIdResolvePostHook>>>>
    export type ResolveReviewItemApiReviewItemsItemIdResolvePostMutationBody = ResolveReviewRequest
    export type ResolveReviewItemApiReviewItemsItemIdResolvePostMutationError = HTTPValidationError

    /**
 * @summary Resolve Review Item
 */
export const useResolveReviewItemApiReviewItemsItemIdResolvePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useResolveReviewItemApiReviewItemsItemIdResolvePostHook>>>, TError,{itemId: string;data: ResolveReviewRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useResolveReviewItemApiReviewItemsItemIdResolvePostHook>>>,
        TError,
        {itemId: string;data: ResolveReviewRequest},
        TContext
      > => {
      return useMutation(useResolveReviewItemApiReviewItemsItemIdResolvePostMutationOptions(options), queryClient);
    }
    /**
 * @summary List Team Decisions
 */
export const useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook = () => {
        const listTeamDecisionsApiTeamsTeamIdDecisionsGet = useCustomInstance<DecisionResponse[]>();

        return useCallback((
    teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams,
 signal?: AbortSignal
) => {
        return listTeamDecisionsApiTeamsTeamIdDecisionsGet(
          {url: `/api/teams/${teamId}/decisions`, method: 'GET',
        params, signal
    },
          );
        }, [listTeamDecisionsApiTeamsTeamIdDecisionsGet])
      }




export const getListTeamDecisionsApiTeamsTeamIdDecisionsGetInfiniteQueryKey = (teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams,) => {
    return [
    'infinite', `/api/teams/${teamId}/decisions`, ...(params ? [params] : [])
    ] as const;
    }

export const getListTeamDecisionsApiTeamsTeamIdDecisionsGetQueryKey = (teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams,) => {
    return [
    `/api/teams/${teamId}/decisions`, ...(params ? [params] : [])
    ] as const;
    }


export const useListTeamDecisionsApiTeamsTeamIdDecisionsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>>, TError = HTTPValidationError>(teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamDecisionsApiTeamsTeamIdDecisionsGetInfiniteQueryKey(teamId,params);

  const listTeamDecisionsApiTeamsTeamIdDecisionsGet =  useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>> = ({ signal }) => listTeamDecisionsApiTeamsTeamIdDecisionsGet(teamId,params, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamDecisionsApiTeamsTeamIdDecisionsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>>
export type ListTeamDecisionsApiTeamsTeamIdDecisionsGetInfiniteQueryError = HTTPValidationError


export function useListTeamDecisionsApiTeamsTeamIdDecisionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string,
    params: undefined |  ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamDecisionsApiTeamsTeamIdDecisionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamDecisionsApiTeamsTeamIdDecisionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Team Decisions
 */

export function useListTeamDecisionsApiTeamsTeamIdDecisionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListTeamDecisionsApiTeamsTeamIdDecisionsGetInfiniteQueryOptions(teamId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListTeamDecisionsApiTeamsTeamIdDecisionsGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamDecisionsApiTeamsTeamIdDecisionsGetQueryKey(teamId,params);

  const listTeamDecisionsApiTeamsTeamIdDecisionsGet =  useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>> = ({ signal }) => listTeamDecisionsApiTeamsTeamIdDecisionsGet(teamId,params, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamDecisionsApiTeamsTeamIdDecisionsGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>>
export type ListTeamDecisionsApiTeamsTeamIdDecisionsGetQueryError = HTTPValidationError


export function useListTeamDecisionsApiTeamsTeamIdDecisionsGet<TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params: undefined |  ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamDecisionsApiTeamsTeamIdDecisionsGet<TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamDecisionsApiTeamsTeamIdDecisionsGet<TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Team Decisions
 */

export function useListTeamDecisionsApiTeamsTeamIdDecisionsGet<TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListTeamDecisionsApiTeamsTeamIdDecisionsGetQueryOptions(teamId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListTeamDecisionsApiTeamsTeamIdDecisionsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamDecisionsApiTeamsTeamIdDecisionsGetQueryKey(teamId,params);

  const listTeamDecisionsApiTeamsTeamIdDecisionsGet =  useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>> = ({ signal }) => listTeamDecisionsApiTeamsTeamIdDecisionsGet(teamId,params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamDecisionsApiTeamsTeamIdDecisionsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>>
export type ListTeamDecisionsApiTeamsTeamIdDecisionsGetSuspenseQueryError = HTTPValidationError


export function useListTeamDecisionsApiTeamsTeamIdDecisionsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params: undefined |  ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamDecisionsApiTeamsTeamIdDecisionsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamDecisionsApiTeamsTeamIdDecisionsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Team Decisions
 */

export function useListTeamDecisionsApiTeamsTeamIdDecisionsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string,
    params?: ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamDecisionsApiTeamsTeamIdDecisionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListTeamDecisionsApiTeamsTeamIdDecisionsGetSuspenseQueryOptions(teamId,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




