/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Ensure Channel
 */
export const EnsureChannelApiOrgsOrgIdChannelsPostParams = zod.object({
  "org_id": zod.uuid()
})

export const EnsureChannelApiOrgsOrgIdChannelsPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})





export const EnsureChannelApiOrgsOrgIdChannelsPostBody = zod.object({
  "team_a_id": zod.string().min(1),
  "team_b_id": zod.string().min(1)
})

/**
 * @summary List Team Channels
 */
export const ListTeamChannelsApiTeamsTeamIdChannelsGetParams = zod.object({
  "team_id": zod.uuid()
})

export const ListTeamChannelsApiTeamsTeamIdChannelsGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListTeamChannelsApiTeamsTeamIdChannelsGetResponseItem = zod.object({
  "id": zod.string(),
  "org_id": zod.string(),
  "team_a_id": zod.string(),
  "team_b_id": zod.string(),
  "team_a_name": zod.union([zod.string(),zod.null()]).optional(),
  "team_b_name": zod.union([zod.string(),zod.null()]).optional(),
  "peer_team_id": zod.union([zod.string(),zod.null()]).optional(),
  "peer_team_name": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const ListTeamChannelsApiTeamsTeamIdChannelsGetResponse = zod.array(ListTeamChannelsApiTeamsTeamIdChannelsGetResponseItem)

/**
 * @summary Create Package
 */
export const CreatePackageApiTeamsTeamIdPackagesPostParams = zod.object({
  "team_id": zod.uuid()
})

export const CreatePackageApiTeamsTeamIdPackagesPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const createPackageApiTeamsTeamIdPackagesPostBodyTitleMax = 512;


export const createPackageApiTeamsTeamIdPackagesPostBodyBypassIncompletePipelineDefault = false;

export const CreatePackageApiTeamsTeamIdPackagesPostBody = zod.object({
  "title": zod.string().min(1).max(createPackageApiTeamsTeamIdPackagesPostBodyTitleMax),
  "body": zod.string().min(1),
  "target_team_id": zod.string(),
  "bypass_incomplete_pipeline": zod.boolean().default(createPackageApiTeamsTeamIdPackagesPostBodyBypassIncompletePipelineDefault),
  "included_node_ids": zod.array(zod.string()).optional()
})

/**
 * @summary Get Package
 */
export const GetPackageApiPackagesPackageIdGetParams = zod.object({
  "package_id": zod.uuid()
})

export const GetPackageApiPackagesPackageIdGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const getPackageApiPackagesPackageIdGetResponseConflictsAcknowledgedDefault = false;

export const GetPackageApiPackagesPackageIdGetResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "target_team_id": zod.string(),
  "channel_id": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "body": zod.string(),
  "status": zod.string(),
  "bypassed_checks": zod.array(zod.string()),
  "checklist": zod.record(zod.string(), zod.unknown()),
  "included_node_ids": zod.array(zod.string()).optional(),
  "conflicts_acknowledged": zod.boolean().default(getPackageApiPackagesPackageIdGetResponseConflictsAcknowledgedDefault),
  "job_id": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary Send Package
 */
export const SendPackageApiPackagesPackageIdSendPostParams = zod.object({
  "package_id": zod.uuid()
})

export const SendPackageApiPackagesPackageIdSendPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const sendPackageApiPackagesPackageIdSendPostBodyOneAcknowledgeConflictsDefault = false;

export const SendPackageApiPackagesPackageIdSendPostBody = zod.union([zod.object({
  "acknowledge_conflicts": zod.boolean().default(sendPackageApiPackagesPackageIdSendPostBodyOneAcknowledgeConflictsDefault)
}),zod.null()])

export const sendPackageApiPackagesPackageIdSendPostResponseConflictsAcknowledgedDefault = false;

export const SendPackageApiPackagesPackageIdSendPostResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "target_team_id": zod.string(),
  "channel_id": zod.union([zod.string(),zod.null()]),
  "title": zod.string(),
  "body": zod.string(),
  "status": zod.string(),
  "bypassed_checks": zod.array(zod.string()),
  "checklist": zod.record(zod.string(), zod.unknown()),
  "included_node_ids": zod.array(zod.string()).optional(),
  "conflicts_acknowledged": zod.boolean().default(sendPackageApiPackagesPackageIdSendPostResponseConflictsAcknowledgedDefault),
  "job_id": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary List Posts
 */
export const ListPostsApiChannelsChannelIdPostsGetParams = zod.object({
  "channel_id": zod.uuid()
})

export const listPostsApiChannelsChannelIdPostsGetQuerySortDefault = `newest`;
export const listPostsApiChannelsChannelIdPostsGetQueryUnreadOnlyDefault = false;

export const ListPostsApiChannelsChannelIdPostsGetQueryParams = zod.object({
  "sort": zod.enum(['priority', 'newest', 'oldest']).default(listPostsApiChannelsChannelIdPostsGetQuerySortDefault),
  "unread_only": zod.boolean().default(listPostsApiChannelsChannelIdPostsGetQueryUnreadOnlyDefault),
  "topic_tags": zod.union([zod.string(),zod.null()]).optional()
})

export const ListPostsApiChannelsChannelIdPostsGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const listPostsApiChannelsChannelIdPostsGetResponseUpdatedSinceSendDefault = false;
export const listPostsApiChannelsChannelIdPostsGetResponseIsReadDefault = false;

export const ListPostsApiChannelsChannelIdPostsGetResponseItem = zod.object({
  "id": zod.string(),
  "channel_id": zod.string(),
  "package_id": zod.string(),
  "version": zod.number(),
  "adapted_body": zod.string(),
  "original_body": zod.string(),
  "what_was_done": zod.string(),
  "ai_priority": zod.union([zod.string(),zod.null()]).optional(),
  "ai_priority_reason": zod.union([zod.string(),zod.null()]).optional(),
  "topic_tags": zod.array(zod.string()).optional(),
  "bypassed_checks": zod.array(zod.string()).optional(),
  "attached_conflicts": zod.array(zod.record(zod.string(), zod.unknown())).optional(),
  "updated_since_send": zod.boolean().default(listPostsApiChannelsChannelIdPostsGetResponseUpdatedSinceSendDefault),
  "is_read": zod.boolean().default(listPostsApiChannelsChannelIdPostsGetResponseIsReadDefault),
  "judge": zod.union([zod.object({
  "fidelity": zod.union([zod.string(),zod.null()]).optional(),
  "fit": zod.union([zod.string(),zod.null()]).optional(),
  "overall_confidence": zod.union([zod.number(),zod.null()]).optional(),
  "badge": zod.union([zod.string(),zod.null()]).optional()
}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const ListPostsApiChannelsChannelIdPostsGetResponse = zod.array(ListPostsApiChannelsChannelIdPostsGetResponseItem)

/**
 * @summary Get Post
 */
export const GetPostApiPostsPostIdGetParams = zod.object({
  "post_id": zod.uuid()
})

export const GetPostApiPostsPostIdGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const getPostApiPostsPostIdGetResponseUpdatedSinceSendDefault = false;
export const getPostApiPostsPostIdGetResponseIsReadDefault = false;

export const GetPostApiPostsPostIdGetResponse = zod.object({
  "id": zod.string(),
  "channel_id": zod.string(),
  "package_id": zod.string(),
  "version": zod.number(),
  "adapted_body": zod.string(),
  "original_body": zod.string(),
  "what_was_done": zod.string(),
  "ai_priority": zod.union([zod.string(),zod.null()]).optional(),
  "ai_priority_reason": zod.union([zod.string(),zod.null()]).optional(),
  "topic_tags": zod.array(zod.string()).optional(),
  "bypassed_checks": zod.array(zod.string()).optional(),
  "attached_conflicts": zod.array(zod.record(zod.string(), zod.unknown())).optional(),
  "updated_since_send": zod.boolean().default(getPostApiPostsPostIdGetResponseUpdatedSinceSendDefault),
  "is_read": zod.boolean().default(getPostApiPostsPostIdGetResponseIsReadDefault),
  "judge": zod.union([zod.object({
  "fidelity": zod.union([zod.string(),zod.null()]).optional(),
  "fit": zod.union([zod.string(),zod.null()]).optional(),
  "overall_confidence": zod.union([zod.number(),zod.null()]).optional(),
  "badge": zod.union([zod.string(),zod.null()]).optional()
}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary List Post History
 */
export const ListPostHistoryApiPostsPostIdHistoryGetParams = zod.object({
  "post_id": zod.uuid()
})

export const ListPostHistoryApiPostsPostIdHistoryGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListPostHistoryApiPostsPostIdHistoryGetResponseItem = zod.object({
  "kind": zod.string(),
  "summary": zod.string(),
  "source": zod.string(),
  "created_at": zod.iso.datetime({}),
  "node_id": zod.union([zod.string(),zod.null()]).optional(),
  "meta": zod.record(zod.string(), zod.unknown()).optional()
})
export const ListPostHistoryApiPostsPostIdHistoryGetResponse = zod.array(ListPostHistoryApiPostsPostIdHistoryGetResponseItem)

/**
 * @summary List Post Sources
 */
export const ListPostSourcesApiPostsPostIdSourcesGetParams = zod.object({
  "post_id": zod.uuid()
})

export const ListPostSourcesApiPostsPostIdSourcesGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListPostSourcesApiPostsPostIdSourcesGetResponse = zod.object({
  "package_id": zod.string(),
  "package_title": zod.string(),
  "documents": zod.array(zod.object({
  "id": zod.string(),
  "filename": zod.string(),
  "status": zod.string()
})).optional()
})

/**
 * @summary Mark Post Read
 */
export const MarkPostReadApiPostsPostIdReadPostParams = zod.object({
  "post_id": zod.uuid()
})

export const MarkPostReadApiPostsPostIdReadPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const markPostReadApiPostsPostIdReadPostResponseUpdatedSinceSendDefault = false;
export const markPostReadApiPostsPostIdReadPostResponseIsReadDefault = false;

export const MarkPostReadApiPostsPostIdReadPostResponse = zod.object({
  "id": zod.string(),
  "channel_id": zod.string(),
  "package_id": zod.string(),
  "version": zod.number(),
  "adapted_body": zod.string(),
  "original_body": zod.string(),
  "what_was_done": zod.string(),
  "ai_priority": zod.union([zod.string(),zod.null()]).optional(),
  "ai_priority_reason": zod.union([zod.string(),zod.null()]).optional(),
  "topic_tags": zod.array(zod.string()).optional(),
  "bypassed_checks": zod.array(zod.string()).optional(),
  "attached_conflicts": zod.array(zod.record(zod.string(), zod.unknown())).optional(),
  "updated_since_send": zod.boolean().default(markPostReadApiPostsPostIdReadPostResponseUpdatedSinceSendDefault),
  "is_read": zod.boolean().default(markPostReadApiPostsPostIdReadPostResponseIsReadDefault),
  "judge": zod.union([zod.object({
  "fidelity": zod.union([zod.string(),zod.null()]).optional(),
  "fit": zod.union([zod.string(),zod.null()]).optional(),
  "overall_confidence": zod.union([zod.number(),zod.null()]).optional(),
  "badge": zod.union([zod.string(),zod.null()]).optional()
}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

