/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  HTTPValidationError,
  InviteAcceptRequest,
  InviteCreate,
  InviteResponse,
  ListMembersApiTeamsTeamIdMembersGet200Item,
  TeamCreate,
  TeamResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * @summary Create Team
 */
export const useCreateTeamApiOrgsOrgIdTeamsPostHook = () => {
        const createTeamApiOrgsOrgIdTeamsPost = useCustomInstance<TeamResponse>();

        return useCallback((
    orgId: string,
    teamCreate: TeamCreate,
 signal?: AbortSignal
) => {
        return createTeamApiOrgsOrgIdTeamsPost(
          {url: `/api/orgs/${orgId}/teams`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: teamCreate, signal
    },
          );
        }, [createTeamApiOrgsOrgIdTeamsPost])
      }



export const useCreateTeamApiOrgsOrgIdTeamsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTeamApiOrgsOrgIdTeamsPostHook>>>, TError,{orgId: string;data: TeamCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTeamApiOrgsOrgIdTeamsPostHook>>>, TError,{orgId: string;data: TeamCreate}, TContext> => {

const mutationKey = ['createTeamApiOrgsOrgIdTeamsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createTeamApiOrgsOrgIdTeamsPost =  useCreateTeamApiOrgsOrgIdTeamsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateTeamApiOrgsOrgIdTeamsPostHook>>>, {orgId: string;data: TeamCreate}> = (props) => {
          const {orgId,data} = props ?? {};

          return  createTeamApiOrgsOrgIdTeamsPost(orgId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTeamApiOrgsOrgIdTeamsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateTeamApiOrgsOrgIdTeamsPostHook>>>>
    export type CreateTeamApiOrgsOrgIdTeamsPostMutationBody = TeamCreate
    export type CreateTeamApiOrgsOrgIdTeamsPostMutationError = HTTPValidationError

    /**
 * @summary Create Team
 */
export const useCreateTeamApiOrgsOrgIdTeamsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateTeamApiOrgsOrgIdTeamsPostHook>>>, TError,{orgId: string;data: TeamCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateTeamApiOrgsOrgIdTeamsPostHook>>>,
        TError,
        {orgId: string;data: TeamCreate},
        TContext
      > => {
      return useMutation(useCreateTeamApiOrgsOrgIdTeamsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Create Invite
 */
export const useCreateInviteApiTeamsTeamIdInvitesPostHook = () => {
        const createInviteApiTeamsTeamIdInvitesPost = useCustomInstance<InviteResponse>();

        return useCallback((
    teamId: string,
    inviteCreate: InviteCreate,
 signal?: AbortSignal
) => {
        return createInviteApiTeamsTeamIdInvitesPost(
          {url: `/api/teams/${teamId}/invites`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: inviteCreate, signal
    },
          );
        }, [createInviteApiTeamsTeamIdInvitesPost])
      }



export const useCreateInviteApiTeamsTeamIdInvitesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateInviteApiTeamsTeamIdInvitesPostHook>>>, TError,{teamId: string;data: InviteCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateInviteApiTeamsTeamIdInvitesPostHook>>>, TError,{teamId: string;data: InviteCreate}, TContext> => {

const mutationKey = ['createInviteApiTeamsTeamIdInvitesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createInviteApiTeamsTeamIdInvitesPost =  useCreateInviteApiTeamsTeamIdInvitesPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateInviteApiTeamsTeamIdInvitesPostHook>>>, {teamId: string;data: InviteCreate}> = (props) => {
          const {teamId,data} = props ?? {};

          return  createInviteApiTeamsTeamIdInvitesPost(teamId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateInviteApiTeamsTeamIdInvitesPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateInviteApiTeamsTeamIdInvitesPostHook>>>>
    export type CreateInviteApiTeamsTeamIdInvitesPostMutationBody = InviteCreate
    export type CreateInviteApiTeamsTeamIdInvitesPostMutationError = HTTPValidationError

    /**
 * @summary Create Invite
 */
export const useCreateInviteApiTeamsTeamIdInvitesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateInviteApiTeamsTeamIdInvitesPostHook>>>, TError,{teamId: string;data: InviteCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateInviteApiTeamsTeamIdInvitesPostHook>>>,
        TError,
        {teamId: string;data: InviteCreate},
        TContext
      > => {
      return useMutation(useCreateInviteApiTeamsTeamIdInvitesPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Accept Invite
 */
export const useAcceptInviteApiInvitesAcceptPostHook = () => {
        const acceptInviteApiInvitesAcceptPost = useCustomInstance<InviteResponse>();

        return useCallback((
    inviteAcceptRequest: InviteAcceptRequest,
 signal?: AbortSignal
) => {
        return acceptInviteApiInvitesAcceptPost(
          {url: `/api/invites/accept`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: inviteAcceptRequest, signal
    },
          );
        }, [acceptInviteApiInvitesAcceptPost])
      }



export const useAcceptInviteApiInvitesAcceptPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAcceptInviteApiInvitesAcceptPostHook>>>, TError,{data: InviteAcceptRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAcceptInviteApiInvitesAcceptPostHook>>>, TError,{data: InviteAcceptRequest}, TContext> => {

const mutationKey = ['acceptInviteApiInvitesAcceptPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const acceptInviteApiInvitesAcceptPost =  useAcceptInviteApiInvitesAcceptPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useAcceptInviteApiInvitesAcceptPostHook>>>, {data: InviteAcceptRequest}> = (props) => {
          const {data} = props ?? {};

          return  acceptInviteApiInvitesAcceptPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AcceptInviteApiInvitesAcceptPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useAcceptInviteApiInvitesAcceptPostHook>>>>
    export type AcceptInviteApiInvitesAcceptPostMutationBody = InviteAcceptRequest
    export type AcceptInviteApiInvitesAcceptPostMutationError = HTTPValidationError

    /**
 * @summary Accept Invite
 */
export const useAcceptInviteApiInvitesAcceptPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useAcceptInviteApiInvitesAcceptPostHook>>>, TError,{data: InviteAcceptRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useAcceptInviteApiInvitesAcceptPostHook>>>,
        TError,
        {data: InviteAcceptRequest},
        TContext
      > => {
      return useMutation(useAcceptInviteApiInvitesAcceptPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove Member
 */
export const useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHook = () => {
        const removeMemberApiTeamsTeamIdMembersUserIdRemovePost = useCustomInstance<void>();

        return useCallback((
    teamId: string,
    userId: string,
 signal?: AbortSignal
) => {
        return removeMemberApiTeamsTeamIdMembersUserIdRemovePost(
          {url: `/api/teams/${teamId}/members/${userId}/remove`, method: 'POST', signal
    },
          );
        }, [removeMemberApiTeamsTeamIdMembersUserIdRemovePost])
      }



export const useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHook>>>, TError,{teamId: string;userId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHook>>>, TError,{teamId: string;userId: string}, TContext> => {

const mutationKey = ['removeMemberApiTeamsTeamIdMembersUserIdRemovePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const removeMemberApiTeamsTeamIdMembersUserIdRemovePost =  useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHook>>>, {teamId: string;userId: string}> = (props) => {
          const {teamId,userId} = props ?? {};

          return  removeMemberApiTeamsTeamIdMembersUserIdRemovePost(teamId,userId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveMemberApiTeamsTeamIdMembersUserIdRemovePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHook>>>>

    export type RemoveMemberApiTeamsTeamIdMembersUserIdRemovePostMutationError = HTTPValidationError

    /**
 * @summary Remove Member
 */
export const useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHook>>>, TError,{teamId: string;userId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHook>>>,
        TError,
        {teamId: string;userId: string},
        TContext
      > => {
      return useMutation(useRemoveMemberApiTeamsTeamIdMembersUserIdRemovePostMutationOptions(options), queryClient);
    }
    /**
 * @summary List Members
 */
export const useListMembersApiTeamsTeamIdMembersGetHook = () => {
        const listMembersApiTeamsTeamIdMembersGet = useCustomInstance<ListMembersApiTeamsTeamIdMembersGet200Item[]>();

        return useCallback((
    teamId: string,
 signal?: AbortSignal
) => {
        return listMembersApiTeamsTeamIdMembersGet(
          {url: `/api/teams/${teamId}/members`, method: 'GET', signal
    },
          );
        }, [listMembersApiTeamsTeamIdMembersGet])
      }




export const getListMembersApiTeamsTeamIdMembersGetInfiniteQueryKey = (teamId: string,) => {
    return [
    'infinite', `/api/teams/${teamId}/members`
    ] as const;
    }

export const getListMembersApiTeamsTeamIdMembersGetQueryKey = (teamId: string,) => {
    return [
    `/api/teams/${teamId}/members`
    ] as const;
    }


export const useListMembersApiTeamsTeamIdMembersGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMembersApiTeamsTeamIdMembersGetInfiniteQueryKey(teamId);

  const listMembersApiTeamsTeamIdMembersGet =  useListMembersApiTeamsTeamIdMembersGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>> = ({ signal }) => listMembersApiTeamsTeamIdMembersGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMembersApiTeamsTeamIdMembersGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>>
export type ListMembersApiTeamsTeamIdMembersGetInfiniteQueryError = HTTPValidationError


export function useListMembersApiTeamsTeamIdMembersGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembersApiTeamsTeamIdMembersGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembersApiTeamsTeamIdMembersGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Members
 */

export function useListMembersApiTeamsTeamIdMembersGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListMembersApiTeamsTeamIdMembersGetInfiniteQueryOptions(teamId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListMembersApiTeamsTeamIdMembersGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMembersApiTeamsTeamIdMembersGetQueryKey(teamId);

  const listMembersApiTeamsTeamIdMembersGet =  useListMembersApiTeamsTeamIdMembersGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>> = ({ signal }) => listMembersApiTeamsTeamIdMembersGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMembersApiTeamsTeamIdMembersGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>>
export type ListMembersApiTeamsTeamIdMembersGetQueryError = HTTPValidationError


export function useListMembersApiTeamsTeamIdMembersGet<TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembersApiTeamsTeamIdMembersGet<TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembersApiTeamsTeamIdMembersGet<TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Members
 */

export function useListMembersApiTeamsTeamIdMembersGet<TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListMembersApiTeamsTeamIdMembersGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListMembersApiTeamsTeamIdMembersGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMembersApiTeamsTeamIdMembersGetQueryKey(teamId);

  const listMembersApiTeamsTeamIdMembersGet =  useListMembersApiTeamsTeamIdMembersGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>> = ({ signal }) => listMembersApiTeamsTeamIdMembersGet(teamId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMembersApiTeamsTeamIdMembersGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>>
export type ListMembersApiTeamsTeamIdMembersGetSuspenseQueryError = HTTPValidationError


export function useListMembersApiTeamsTeamIdMembersGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembersApiTeamsTeamIdMembersGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembersApiTeamsTeamIdMembersGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Members
 */

export function useListMembersApiTeamsTeamIdMembersGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListMembersApiTeamsTeamIdMembersGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListMembersApiTeamsTeamIdMembersGetSuspenseQueryOptions(teamId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




