/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Review Items
 */
export const ListReviewItemsApiTeamsTeamIdReviewItemsGetParams = zod.object({
  "team_id": zod.uuid()
})

export const ListReviewItemsApiTeamsTeamIdReviewItemsGetQueryParams = zod.object({
  "status": zod.union([zod.string(),zod.null()]).optional()
})

export const ListReviewItemsApiTeamsTeamIdReviewItemsGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListReviewItemsApiTeamsTeamIdReviewItemsGetResponseItem = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "claim_a_id": zod.string(),
  "claim_b_id": zod.string(),
  "conflict_class": zod.string(),
  "severity": zod.string(),
  "rationale": zod.string(),
  "matched_via": zod.string(),
  "status": zod.string(),
  "proposed_resolution": zod.union([zod.string(),zod.null()]).optional(),
  "resolved_resolution": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const ListReviewItemsApiTeamsTeamIdReviewItemsGetResponse = zod.array(ListReviewItemsApiTeamsTeamIdReviewItemsGetResponseItem)

/**
 * @summary Propose Resolution
 */
export const ProposeResolutionApiReviewItemsItemIdProposePostParams = zod.object({
  "item_id": zod.uuid()
})

export const ProposeResolutionApiReviewItemsItemIdProposePostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ProposeResolutionApiReviewItemsItemIdProposePostBody = zod.object({
  "resolution": zod.enum(['keep_a', 'keep_b', 'keep_both', 'not_a_conflict'])
})

export const ProposeResolutionApiReviewItemsItemIdProposePostResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "claim_a_id": zod.string(),
  "claim_b_id": zod.string(),
  "conflict_class": zod.string(),
  "severity": zod.string(),
  "rationale": zod.string(),
  "matched_via": zod.string(),
  "status": zod.string(),
  "proposed_resolution": zod.union([zod.string(),zod.null()]).optional(),
  "resolved_resolution": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary Resolve Review Item
 */
export const ResolveReviewItemApiReviewItemsItemIdResolvePostParams = zod.object({
  "item_id": zod.uuid()
})

export const ResolveReviewItemApiReviewItemsItemIdResolvePostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ResolveReviewItemApiReviewItemsItemIdResolvePostBody = zod.object({
  "resolution": zod.enum(['keep_a', 'keep_b', 'keep_both', 'not_a_conflict'])
})

export const ResolveReviewItemApiReviewItemsItemIdResolvePostResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "claim_a_id": zod.string(),
  "claim_b_id": zod.string(),
  "conflict_class": zod.string(),
  "severity": zod.string(),
  "rationale": zod.string(),
  "matched_via": zod.string(),
  "status": zod.string(),
  "proposed_resolution": zod.union([zod.string(),zod.null()]).optional(),
  "resolved_resolution": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary List Team Decisions
 */
export const ListTeamDecisionsApiTeamsTeamIdDecisionsGetParams = zod.object({
  "team_id": zod.uuid()
})

export const listTeamDecisionsApiTeamsTeamIdDecisionsGetQueryStatusDefault = `all`;

export const ListTeamDecisionsApiTeamsTeamIdDecisionsGetQueryParams = zod.object({
  "status": zod.union([zod.string(),zod.null()]).default(listTeamDecisionsApiTeamsTeamIdDecisionsGetQueryStatusDefault)
})

export const ListTeamDecisionsApiTeamsTeamIdDecisionsGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const listTeamDecisionsApiTeamsTeamIdDecisionsGetResponseStatusDefault = `open`;

export const ListTeamDecisionsApiTeamsTeamIdDecisionsGetResponseItem = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "claim_id": zod.string(),
  "title": zod.string(),
  "body": zod.string(),
  "source": zod.string(),
  "status": zod.string().default(listTeamDecisionsApiTeamsTeamIdDecisionsGetResponseStatusDefault),
  "owner_team_id": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const ListTeamDecisionsApiTeamsTeamIdDecisionsGetResponse = zod.array(ListTeamDecisionsApiTeamsTeamIdDecisionsGetResponseItem)

