/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * List notifications for the authenticated user within the active org.
 * @summary List Notifications
 */
export const listNotificationsApiNotificationsGetQueryUnreadOnlyDefault = false;
export const listNotificationsApiNotificationsGetQueryLimitDefault = 50;
export const listNotificationsApiNotificationsGetQueryLimitMax = 100;



export const ListNotificationsApiNotificationsGetQueryParams = zod.object({
  "unread_only": zod.boolean().default(listNotificationsApiNotificationsGetQueryUnreadOnlyDefault),
  "limit": zod.number().min(1).max(listNotificationsApiNotificationsGetQueryLimitMax).default(listNotificationsApiNotificationsGetQueryLimitDefault)
})

export const ListNotificationsApiNotificationsGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListNotificationsApiNotificationsGetResponseItem = zod.object({
  "id": zod.string(),
  "org_id": zod.string(),
  "user_id": zod.string(),
  "kind": zod.string(),
  "payload": zod.record(zod.string(), zod.unknown()),
  "read_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const ListNotificationsApiNotificationsGetResponse = zod.array(ListNotificationsApiNotificationsGetResponseItem)

