/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface AdminMetricsResponse {
  trace_count: number;
  total_cost_usd: number;
  average_latency_ms?: number | null;
  job_count: number;
  job_pass_rate?: number | null;
  post_count: number;
  package_count: number;
  suggestion_count: number;
  conflict_false_positive_rate?: number | null;
  conflict_resolved_count?: number;
  conflict_not_a_conflict_count?: number;
}
