/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { PostResponse } from './post-response';

/**
 * Paginated channel feed (search + page).
 */
export interface ChannelPostsPage {
  items?: PostResponse[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
  q?: string | null;
}
