/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface ChannelResponse {
  id: string;
  org_id: string;
  team_a_id: string;
  team_b_id: string;
  team_a_name?: string | null;
  team_b_name?: string | null;
  peer_team_id?: string | null;
  peer_team_name?: string | null;
  created_at: string;
}
