/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface CommentResponse {
  id: string;
  post_id: string;
  author_team_id: string;
  original_body: string;
  adapted_body?: string | null;
  created_at: string;
}
