/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface DecisionResponse {
  id: string;
  team_id: string;
  claim_id: string;
  title: string;
  body: string;
  source: string;
  status?: string;
  owner_team_id?: string | null;
  owner_team_name?: string | null;
  channel_id?: string | null;
  superseded_by?: string | null;
  created_at: string;
}
