/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentResponse {
  id: string;
  team_id: string;
  org_id: string;
  filename: string;
  status: string;
  storage_uri?: string | null;
  job_id?: string | null;
  created_at: string;
}
