/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface EnsureChannelBody {
  /** @minLength 1 */
  team_a_id: string;
  /** @minLength 1 */
  team_b_id: string;
}
