/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type GetNodeDiffApiNodesNodeIdDiffGetParams = {
/**
 * @minimum 1
 */
from_version: number;
/**
 * @minimum 1
 */
to_version: number;
};
