/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { GlossaryTermResponseKind } from './glossary-term-response-kind';

export interface GlossaryTermResponse {
  id: string;
  team_id: string;
  term: string;
  definition: string;
  kind: GlossaryTermResponseKind;
  created_at: string;
  updated_at: string;
}
