/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type GlossaryTermCreateKind = typeof GlossaryTermCreateKind[keyof typeof GlossaryTermCreateKind];


export const GlossaryTermCreateKind = {
  known: 'known',
  must_explain: 'must_explain',
} as const;
