/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { GlossaryTermCreateKind } from './glossary-term-create-kind';

export interface GlossaryTermCreate {
  /**
     * @minLength 1
     * @maxLength 255
     */
  term: string;
  /** @minLength 1 */
  definition: string;
  kind?: GlossaryTermCreateKind;
}
