/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type GlossaryTermResponseKind = typeof GlossaryTermResponseKind[keyof typeof GlossaryTermResponseKind];


export const GlossaryTermResponseKind = {
  known: 'known',
  must_explain: 'must_explain',
} as const;
