/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { GoldenExampleCreateExpectedJson } from './golden-example-create-expected-json';
import type { GoldenExampleCreateInputJson } from './golden-example-create-input-json';
import type { GoldenExampleCreateKind } from './golden-example-create-kind';

export interface GoldenExampleCreate {
  kind: GoldenExampleCreateKind;
  input_json: GoldenExampleCreateInputJson;
  expected_json: GoldenExampleCreateExpectedJson;
  notes?: string | null;
}
