/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { GoldenExampleUpdateExpectedJson } from './golden-example-update-expected-json';
import type { GoldenExampleUpdateInputJson } from './golden-example-update-input-json';

export interface GoldenExampleUpdate {
  kind?: 'conflict' | 'judge' | 'fidelity' | null;
  input_json?: GoldenExampleUpdateInputJson;
  expected_json?: GoldenExampleUpdateExpectedJson;
  notes?: string | null;
}
