/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { GoldenExampleResponseExpectedJson } from './golden-example-response-expected-json';
import type { GoldenExampleResponseInputJson } from './golden-example-response-input-json';
import type { GoldenExampleResponseKind } from './golden-example-response-kind';

export interface GoldenExampleResponse {
  id: string;
  org_id: string;
  kind: GoldenExampleResponseKind;
  input_json: GoldenExampleResponseInputJson;
  expected_json: GoldenExampleResponseExpectedJson;
  notes: string | null;
  created_at: string;
}
