/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type GoldenExampleCreateKind = typeof GoldenExampleCreateKind[keyof typeof GoldenExampleCreateKind];


export const GoldenExampleCreateKind = {
  conflict: 'conflict',
  judge: 'judge',
  fidelity: 'fidelity',
} as const;
