/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type GoldenExampleResponseKind = typeof GoldenExampleResponseKind[keyof typeof GoldenExampleResponseKind];


export const GoldenExampleResponseKind = {
  conflict: 'conflict',
  judge: 'judge',
  fidelity: 'fidelity',
} as const;
