/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface InviteResponse {
  id: string;
  team_id: string;
  email: string;
  role: string;
  token: string;
  created_at: string;
  added_immediately?: boolean;
}
