/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface InviteCreate {
  /**
     * @minLength 3
     * @maxLength 255
     */
  email: string;
  role?: string;
}
