/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Invite by email and/or username (at least one required).
 */
export interface InviteCreate {
  email?: string | null;
  username?: string | null;
  role?: string;
}
