/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface JudgeSummary {
  fidelity?: string | null;
  fit?: string | null;
  overall_confidence?: number | null;
  badge?: string | null;
}
