/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type ListNotificationsApiNotificationsGetParams = {
unread_only?: boolean;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
