/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ListPostsApiChannelsChannelIdPostsGetSort } from './list-posts-api-channels-channel-id-posts-get-sort';

export type ListPostsApiChannelsChannelIdPostsGetParams = {
sort?: ListPostsApiChannelsChannelIdPostsGetSort;
unread_only?: boolean;
topic_tags?: string | null;
};
