/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type ListPostsApiChannelsChannelIdPostsGetSort = typeof ListPostsApiChannelsChannelIdPostsGetSort[keyof typeof ListPostsApiChannelsChannelIdPostsGetSort];


export const ListPostsApiChannelsChannelIdPostsGetSort = {
  priority: 'priority',
  newest: 'newest',
  oldest: 'oldest',
} as const;
