/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface NodeResponse {
  id: string;
  team_id: string;
  org_id: string;
  label: string;
  node_type: string;
  summary: string;
  parent_id?: string | null;
  version: number;
  document_id?: string | null;
  created_at: string;
}
