/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { NodeHistoryResponseSnapshot } from './node-history-response-snapshot';

export interface NodeHistoryResponse {
  id: string;
  node_id: string;
  version: number;
  snapshot?: NodeHistoryResponseSnapshot;
  source: string;
  created_at: string;
}
