/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface NodeDiffResponse {
  node_id: string;
  from_version: number;
  to_version: number;
  diff: string;
}
