/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationResponsePayload } from './notification-response-payload';

export interface NotificationResponse {
  id: string;
  org_id: string;
  user_id: string;
  kind: string;
  payload: NotificationResponsePayload;
  read_at?: string | null;
  created_at: string;
}
