/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface OrgCreate {
  /**
     * @minLength 1
     * @maxLength 255
     */
  name: string;
}
