/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { PackageResponseChecklist } from './package-response-checklist';

export interface PackageResponse {
  id: string;
  team_id: string;
  target_team_id: string;
  channel_id: string | null;
  title: string;
  body: string;
  status: string;
  bypassed_checks: string[];
  checklist: PackageResponseChecklist;
  included_node_ids?: string[];
  conflicts_acknowledged?: boolean;
  job_id?: string | null;
  created_at: string;
}
