/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface PackageCreate {
  /**
     * @minLength 1
     * @maxLength 512
     */
  title: string;
  /** @minLength 1 */
  body: string;
  target_team_id: string;
  bypass_incomplete_pipeline?: boolean;
  included_node_ids?: string[];
}
