/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface PasteDocumentBody {
  /** @minLength 1 */
  text: string;
  /**
     * @minLength 1
     * @maxLength 255
     */
  filename?: string;
}
