/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { PostHistoryEntryMeta } from './post-history-entry-meta';

export interface PostHistoryEntry {
  kind: string;
  summary: string;
  source: string;
  created_at: string;
  node_id?: string | null;
  meta?: PostHistoryEntryMeta;
}
