/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { JudgeSummary } from './judge-summary';
import type { PostResponseAttachedConflictsItem } from './post-response-attached-conflicts-item';

export interface PostResponse {
  id: string;
  channel_id: string;
  package_id: string;
  package_title?: string | null;
  version: number;
  adapted_body: string;
  original_body: string;
  what_was_done: string;
  ai_priority?: string | null;
  ai_priority_reason?: string | null;
  topic_tags?: string[];
  bypassed_checks?: string[];
  attached_conflicts?: PostResponseAttachedConflictsItem[];
  updated_since_send?: boolean;
  is_read?: boolean;
  judge?: JudgeSummary | null;
  sender_team_id?: string | null;
  sender_team_name?: string | null;
  sender_name?: string | null;
  created_at: string;
  search_score?: number | null;
}
