/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { PostSourceDocument } from './post-source-document';

export interface PostSourcesResponse {
  package_id: string;
  package_title: string;
  documents?: PostSourceDocument[];
}
