/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type ProfileDraftResponseGeneratedBy = typeof ProfileDraftResponseGeneratedBy[keyof typeof ProfileDraftResponseGeneratedBy];


export const ProfileDraftResponseGeneratedBy = {
  mistral: 'mistral',
  deterministic_stub: 'deterministic_stub',
} as const;
