/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface ProfileDraftData {
  purpose: string;
  audiences?: string[];
  tone: string;
  communication_preferences?: string[];
  known_terms?: string[];
}
