/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ProfileResponseData } from './profile-response-data';

export interface ProfileResponse {
  id: string;
  team_id: string;
  version: number;
  data: ProfileResponseData;
  created_at: string;
}
