/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ProfileDraftData } from './profile-draft-data';
import type { ProfileDraftResponseGeneratedBy } from './profile-draft-response-generated-by';

export interface ProfileDraftResponse {
  document_id: string;
  data: ProfileDraftData;
  generated_by: ProfileDraftResponseGeneratedBy;
}
