/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type ProposeResolutionRequestResolution = typeof ProposeResolutionRequestResolution[keyof typeof ProposeResolutionRequestResolution];


export const ProposeResolutionRequestResolution = {
  keep_a: 'keep_a',
  keep_b: 'keep_b',
  keep_both: 'keep_both',
  not_a_conflict: 'not_a_conflict',
} as const;
