/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ProposeResolutionRequestResolution } from './propose-resolution-request-resolution';

export interface ProposeResolutionRequest {
  resolution: ProposeResolutionRequestResolution;
}
