/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewActionCreateAction } from './review-action-create-action';

export interface ReviewActionCreate {
  action: ReviewActionCreateAction;
  note?: string | null;
}
