/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface ReviewActionResponse {
  id: string;
  post_id: string;
  team_id: string;
  action: string;
  note?: string | null;
  created_at: string;
}
