/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface ReviewItemResponse {
  id: string;
  team_id: string;
  claim_a_id: string;
  claim_b_id: string;
  conflict_class: string;
  severity: string;
  rationale: string;
  matched_via: string;
  status: string;
  proposed_resolution?: string | null;
  resolved_resolution?: string | null;
  created_at: string;
}
