/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type ReviewActionCreateAction = typeof ReviewActionCreateAction[keyof typeof ReviewActionCreateAction];


export const ReviewActionCreateAction = {
  agree: 'agree',
  request_changes: 'request_changes',
  blocked: 'blocked',
} as const;
