/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface SuggestionResponse {
  id: string;
  post_id: string;
  package_id: string;
  proposer_team_id: string;
  target_team_id: string;
  original_text: string;
  adapted_preview?: string | null;
  proposed_text?: string | null;
  status: string;
  response?: string | null;
  response_reason?: string | null;
  target_node_id?: string | null;
  target_node_version?: number | null;
  suggestion_type?: 'edit_text' | 'add_detail' | 'flag_incorrect' | 'request_clarification' | 'propose_alternative' | null;
  approved_team_ids?: string[];
  awaiting_team_ids?: string[];
  applied_at?: string | null;
  created_at: string;
}
