/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface SuggestionCreate {
  /** @minLength 1 */
  text: string;
  target_node_id?: string | null;
  suggestion_type?: 'edit_text' | 'add_detail' | 'flag_incorrect' | 'request_clarification' | 'propose_alternative' | null;
}
