/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type SuggestionRespondResponse = typeof SuggestionRespondResponse[keyof typeof SuggestionRespondResponse];


export const SuggestionRespondResponse = {
  accept: 'accept',
  edit: 'edit',
  reject: 'reject',
} as const;
