/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { SuggestionRespondResponse } from './suggestion-respond-response';

export interface SuggestionRespond {
  response: SuggestionRespondResponse;
  reason?: string | null;
  edited_text?: string | null;
}
