/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  HTTPValidationError,
  ListNotificationsApiNotificationsGetParams,
  NotificationResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * List notifications for the authenticated user within the active org.
 * @summary List Notifications
 */
export const useListNotificationsApiNotificationsGetHook = () => {
        const listNotificationsApiNotificationsGet = useCustomInstance<NotificationResponse[]>();

        return useCallback((
    params?: ListNotificationsApiNotificationsGetParams,
 signal?: AbortSignal
) => {
        return listNotificationsApiNotificationsGet(
          {url: `/api/notifications`, method: 'GET',
        params, signal
    },
          );
        }, [listNotificationsApiNotificationsGet])
      }




export const getListNotificationsApiNotificationsGetInfiniteQueryKey = (params?: ListNotificationsApiNotificationsGetParams,) => {
    return [
    'infinite', `/api/notifications`, ...(params ? [params] : [])
    ] as const;
    }

export const getListNotificationsApiNotificationsGetQueryKey = (params?: ListNotificationsApiNotificationsGetParams,) => {
    return [
    `/api/notifications`, ...(params ? [params] : [])
    ] as const;
    }


export const useListNotificationsApiNotificationsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>>, TError = HTTPValidationError>(params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNotificationsApiNotificationsGetInfiniteQueryKey(params);

  const listNotificationsApiNotificationsGet =  useListNotificationsApiNotificationsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>> = ({ signal }) => listNotificationsApiNotificationsGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListNotificationsApiNotificationsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>>
export type ListNotificationsApiNotificationsGetInfiniteQueryError = HTTPValidationError


export function useListNotificationsApiNotificationsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>>, TError = HTTPValidationError>(
 params: undefined |  ListNotificationsApiNotificationsGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotificationsApiNotificationsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotificationsApiNotificationsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Notifications
 */

export function useListNotificationsApiNotificationsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListNotificationsApiNotificationsGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListNotificationsApiNotificationsGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNotificationsApiNotificationsGetQueryKey(params);

  const listNotificationsApiNotificationsGet =  useListNotificationsApiNotificationsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>> = ({ signal }) => listNotificationsApiNotificationsGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListNotificationsApiNotificationsGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>>
export type ListNotificationsApiNotificationsGetQueryError = HTTPValidationError


export function useListNotificationsApiNotificationsGet<TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(
 params: undefined |  ListNotificationsApiNotificationsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotificationsApiNotificationsGet<TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotificationsApiNotificationsGet<TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Notifications
 */

export function useListNotificationsApiNotificationsGet<TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListNotificationsApiNotificationsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListNotificationsApiNotificationsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNotificationsApiNotificationsGetQueryKey(params);

  const listNotificationsApiNotificationsGet =  useListNotificationsApiNotificationsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>> = ({ signal }) => listNotificationsApiNotificationsGet(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListNotificationsApiNotificationsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>>
export type ListNotificationsApiNotificationsGetSuspenseQueryError = HTTPValidationError


export function useListNotificationsApiNotificationsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(
 params: undefined |  ListNotificationsApiNotificationsGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotificationsApiNotificationsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListNotificationsApiNotificationsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Notifications
 */

export function useListNotificationsApiNotificationsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError = HTTPValidationError>(
 params?: ListNotificationsApiNotificationsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListNotificationsApiNotificationsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListNotificationsApiNotificationsGetSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




