/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  GlossaryTermCreate,
  GlossaryTermResponse,
  GlossaryTermUpdate,
  HTTPValidationError
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * @summary List Glossary
 */
export const useListGlossaryApiTeamsTeamIdGlossaryGetHook = () => {
        const listGlossaryApiTeamsTeamIdGlossaryGet = useCustomInstance<GlossaryTermResponse[]>();

        return useCallback((
    teamId: string,
 signal?: AbortSignal
) => {
        return listGlossaryApiTeamsTeamIdGlossaryGet(
          {url: `/api/teams/${teamId}/glossary`, method: 'GET', signal
    },
          );
        }, [listGlossaryApiTeamsTeamIdGlossaryGet])
      }




export const getListGlossaryApiTeamsTeamIdGlossaryGetInfiniteQueryKey = (teamId: string,) => {
    return [
    'infinite', `/api/teams/${teamId}/glossary`
    ] as const;
    }

export const getListGlossaryApiTeamsTeamIdGlossaryGetQueryKey = (teamId: string,) => {
    return [
    `/api/teams/${teamId}/glossary`
    ] as const;
    }


export const useListGlossaryApiTeamsTeamIdGlossaryGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGlossaryApiTeamsTeamIdGlossaryGetInfiniteQueryKey(teamId);

  const listGlossaryApiTeamsTeamIdGlossaryGet =  useListGlossaryApiTeamsTeamIdGlossaryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>> = ({ signal }) => listGlossaryApiTeamsTeamIdGlossaryGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGlossaryApiTeamsTeamIdGlossaryGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>>
export type ListGlossaryApiTeamsTeamIdGlossaryGetInfiniteQueryError = HTTPValidationError


export function useListGlossaryApiTeamsTeamIdGlossaryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGlossaryApiTeamsTeamIdGlossaryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGlossaryApiTeamsTeamIdGlossaryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Glossary
 */

export function useListGlossaryApiTeamsTeamIdGlossaryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListGlossaryApiTeamsTeamIdGlossaryGetInfiniteQueryOptions(teamId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListGlossaryApiTeamsTeamIdGlossaryGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGlossaryApiTeamsTeamIdGlossaryGetQueryKey(teamId);

  const listGlossaryApiTeamsTeamIdGlossaryGet =  useListGlossaryApiTeamsTeamIdGlossaryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>> = ({ signal }) => listGlossaryApiTeamsTeamIdGlossaryGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGlossaryApiTeamsTeamIdGlossaryGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>>
export type ListGlossaryApiTeamsTeamIdGlossaryGetQueryError = HTTPValidationError


export function useListGlossaryApiTeamsTeamIdGlossaryGet<TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGlossaryApiTeamsTeamIdGlossaryGet<TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGlossaryApiTeamsTeamIdGlossaryGet<TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Glossary
 */

export function useListGlossaryApiTeamsTeamIdGlossaryGet<TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListGlossaryApiTeamsTeamIdGlossaryGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListGlossaryApiTeamsTeamIdGlossaryGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGlossaryApiTeamsTeamIdGlossaryGetQueryKey(teamId);

  const listGlossaryApiTeamsTeamIdGlossaryGet =  useListGlossaryApiTeamsTeamIdGlossaryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>> = ({ signal }) => listGlossaryApiTeamsTeamIdGlossaryGet(teamId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGlossaryApiTeamsTeamIdGlossaryGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>>
export type ListGlossaryApiTeamsTeamIdGlossaryGetSuspenseQueryError = HTTPValidationError


export function useListGlossaryApiTeamsTeamIdGlossaryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGlossaryApiTeamsTeamIdGlossaryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGlossaryApiTeamsTeamIdGlossaryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Glossary
 */

export function useListGlossaryApiTeamsTeamIdGlossaryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListGlossaryApiTeamsTeamIdGlossaryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListGlossaryApiTeamsTeamIdGlossaryGetSuspenseQueryOptions(teamId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Glossary Term
 */
export const useCreateGlossaryTermApiTeamsTeamIdGlossaryPostHook = () => {
        const createGlossaryTermApiTeamsTeamIdGlossaryPost = useCustomInstance<GlossaryTermResponse>();

        return useCallback((
    teamId: string,
    glossaryTermCreate: GlossaryTermCreate,
 signal?: AbortSignal
) => {
        return createGlossaryTermApiTeamsTeamIdGlossaryPost(
          {url: `/api/teams/${teamId}/glossary`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: glossaryTermCreate, signal
    },
          );
        }, [createGlossaryTermApiTeamsTeamIdGlossaryPost])
      }



export const useCreateGlossaryTermApiTeamsTeamIdGlossaryPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateGlossaryTermApiTeamsTeamIdGlossaryPostHook>>>, TError,{teamId: string;data: GlossaryTermCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateGlossaryTermApiTeamsTeamIdGlossaryPostHook>>>, TError,{teamId: string;data: GlossaryTermCreate}, TContext> => {

const mutationKey = ['createGlossaryTermApiTeamsTeamIdGlossaryPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createGlossaryTermApiTeamsTeamIdGlossaryPost =  useCreateGlossaryTermApiTeamsTeamIdGlossaryPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateGlossaryTermApiTeamsTeamIdGlossaryPostHook>>>, {teamId: string;data: GlossaryTermCreate}> = (props) => {
          const {teamId,data} = props ?? {};

          return  createGlossaryTermApiTeamsTeamIdGlossaryPost(teamId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateGlossaryTermApiTeamsTeamIdGlossaryPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateGlossaryTermApiTeamsTeamIdGlossaryPostHook>>>>
    export type CreateGlossaryTermApiTeamsTeamIdGlossaryPostMutationBody = GlossaryTermCreate
    export type CreateGlossaryTermApiTeamsTeamIdGlossaryPostMutationError = HTTPValidationError

    /**
 * @summary Create Glossary Term
 */
export const useCreateGlossaryTermApiTeamsTeamIdGlossaryPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateGlossaryTermApiTeamsTeamIdGlossaryPostHook>>>, TError,{teamId: string;data: GlossaryTermCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateGlossaryTermApiTeamsTeamIdGlossaryPostHook>>>,
        TError,
        {teamId: string;data: GlossaryTermCreate},
        TContext
      > => {
      return useMutation(useCreateGlossaryTermApiTeamsTeamIdGlossaryPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Glossary Term
 */
export const useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHook = () => {
        const updateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatch = useCustomInstance<GlossaryTermResponse>();

        return useCallback((
    teamId: string,
    termId: string,
    glossaryTermUpdate: GlossaryTermUpdate,
 signal?: AbortSignal
) => {
        return updateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatch(
          {url: `/api/teams/${teamId}/glossary/${termId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: glossaryTermUpdate, signal
    },
          );
        }, [updateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatch])
      }



export const useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHook>>>, TError,{teamId: string;termId: string;data: GlossaryTermUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHook>>>, TError,{teamId: string;termId: string;data: GlossaryTermUpdate}, TContext> => {

const mutationKey = ['updateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const updateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatch =  useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHook>>>, {teamId: string;termId: string;data: GlossaryTermUpdate}> = (props) => {
          const {teamId,termId,data} = props ?? {};

          return  updateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatch(teamId,termId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHook>>>>
    export type UpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchMutationBody = GlossaryTermUpdate
    export type UpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Glossary Term
 */
export const useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHook>>>, TError,{teamId: string;termId: string;data: GlossaryTermUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHook>>>,
        TError,
        {teamId: string;termId: string;data: GlossaryTermUpdate},
        TContext
      > => {
      return useMutation(useUpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Glossary Term
 */
export const useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHook = () => {
        const deleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDelete = useCustomInstance<void>();

        return useCallback((
    teamId: string,
    termId: string,
 signal?: AbortSignal
) => {
        return deleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDelete(
          {url: `/api/teams/${teamId}/glossary/${termId}`, method: 'DELETE', signal
    },
          );
        }, [deleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDelete])
      }



export const useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHook>>>, TError,{teamId: string;termId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHook>>>, TError,{teamId: string;termId: string}, TContext> => {

const mutationKey = ['deleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const deleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDelete =  useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHook>>>, {teamId: string;termId: string}> = (props) => {
          const {teamId,termId} = props ?? {};

          return  deleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDelete(teamId,termId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHook>>>>

    export type DeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Glossary Term
 */
export const useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHook>>>, TError,{teamId: string;termId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHook>>>,
        TError,
        {teamId: string;termId: string},
        TContext
      > => {
      return useMutation(useDeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteMutationOptions(options), queryClient);
    }
