/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  ChannelResponse,
  EnsureChannelBody,
  HTTPValidationError,
  ListPostsApiChannelsChannelIdPostsGetParams,
  PackageCreate,
  PackageResponse,
  PackageSendBody,
  PostHistoryEntry,
  PostResponse,
  PostSourcesResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * @summary Ensure Channel
 */
export const useEnsureChannelApiOrgsOrgIdChannelsPostHook = () => {
        const ensureChannelApiOrgsOrgIdChannelsPost = useCustomInstance<ChannelResponse>();

        return useCallback((
    orgId: string,
    ensureChannelBody: EnsureChannelBody,
 signal?: AbortSignal
) => {
        return ensureChannelApiOrgsOrgIdChannelsPost(
          {url: `/api/orgs/${orgId}/channels`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ensureChannelBody, signal
    },
          );
        }, [ensureChannelApiOrgsOrgIdChannelsPost])
      }



export const useEnsureChannelApiOrgsOrgIdChannelsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEnsureChannelApiOrgsOrgIdChannelsPostHook>>>, TError,{orgId: string;data: EnsureChannelBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEnsureChannelApiOrgsOrgIdChannelsPostHook>>>, TError,{orgId: string;data: EnsureChannelBody}, TContext> => {

const mutationKey = ['ensureChannelApiOrgsOrgIdChannelsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const ensureChannelApiOrgsOrgIdChannelsPost =  useEnsureChannelApiOrgsOrgIdChannelsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useEnsureChannelApiOrgsOrgIdChannelsPostHook>>>, {orgId: string;data: EnsureChannelBody}> = (props) => {
          const {orgId,data} = props ?? {};

          return  ensureChannelApiOrgsOrgIdChannelsPost(orgId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EnsureChannelApiOrgsOrgIdChannelsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useEnsureChannelApiOrgsOrgIdChannelsPostHook>>>>
    export type EnsureChannelApiOrgsOrgIdChannelsPostMutationBody = EnsureChannelBody
    export type EnsureChannelApiOrgsOrgIdChannelsPostMutationError = HTTPValidationError

    /**
 * @summary Ensure Channel
 */
export const useEnsureChannelApiOrgsOrgIdChannelsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useEnsureChannelApiOrgsOrgIdChannelsPostHook>>>, TError,{orgId: string;data: EnsureChannelBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useEnsureChannelApiOrgsOrgIdChannelsPostHook>>>,
        TError,
        {orgId: string;data: EnsureChannelBody},
        TContext
      > => {
      return useMutation(useEnsureChannelApiOrgsOrgIdChannelsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Create Package
 */
export const useCreatePackageApiTeamsTeamIdPackagesPostHook = () => {
        const createPackageApiTeamsTeamIdPackagesPost = useCustomInstance<PackageResponse>();

        return useCallback((
    teamId: string,
    packageCreate: PackageCreate,
 signal?: AbortSignal
) => {
        return createPackageApiTeamsTeamIdPackagesPost(
          {url: `/api/teams/${teamId}/packages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: packageCreate, signal
    },
          );
        }, [createPackageApiTeamsTeamIdPackagesPost])
      }



export const useCreatePackageApiTeamsTeamIdPackagesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreatePackageApiTeamsTeamIdPackagesPostHook>>>, TError,{teamId: string;data: PackageCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreatePackageApiTeamsTeamIdPackagesPostHook>>>, TError,{teamId: string;data: PackageCreate}, TContext> => {

const mutationKey = ['createPackageApiTeamsTeamIdPackagesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createPackageApiTeamsTeamIdPackagesPost =  useCreatePackageApiTeamsTeamIdPackagesPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreatePackageApiTeamsTeamIdPackagesPostHook>>>, {teamId: string;data: PackageCreate}> = (props) => {
          const {teamId,data} = props ?? {};

          return  createPackageApiTeamsTeamIdPackagesPost(teamId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePackageApiTeamsTeamIdPackagesPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreatePackageApiTeamsTeamIdPackagesPostHook>>>>
    export type CreatePackageApiTeamsTeamIdPackagesPostMutationBody = PackageCreate
    export type CreatePackageApiTeamsTeamIdPackagesPostMutationError = HTTPValidationError

    /**
 * @summary Create Package
 */
export const useCreatePackageApiTeamsTeamIdPackagesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreatePackageApiTeamsTeamIdPackagesPostHook>>>, TError,{teamId: string;data: PackageCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreatePackageApiTeamsTeamIdPackagesPostHook>>>,
        TError,
        {teamId: string;data: PackageCreate},
        TContext
      > => {
      return useMutation(useCreatePackageApiTeamsTeamIdPackagesPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Package
 */
export const useGetPackageApiPackagesPackageIdGetHook = () => {
        const getPackageApiPackagesPackageIdGet = useCustomInstance<PackageResponse>();

        return useCallback((
    packageId: string,
 signal?: AbortSignal
) => {
        return getPackageApiPackagesPackageIdGet(
          {url: `/api/packages/${packageId}`, method: 'GET', signal
    },
          );
        }, [getPackageApiPackagesPackageIdGet])
      }




export const getGetPackageApiPackagesPackageIdGetInfiniteQueryKey = (packageId: string,) => {
    return [
    'infinite', `/api/packages/${packageId}`
    ] as const;
    }

export const getGetPackageApiPackagesPackageIdGetQueryKey = (packageId: string,) => {
    return [
    `/api/packages/${packageId}`
    ] as const;
    }


export const useGetPackageApiPackagesPackageIdGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>>, TError = HTTPValidationError>(packageId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPackageApiPackagesPackageIdGetInfiniteQueryKey(packageId);

  const getPackageApiPackagesPackageIdGet =  useGetPackageApiPackagesPackageIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>> = ({ signal }) => getPackageApiPackagesPackageIdGet(packageId, signal);





   return  { queryKey, queryFn, enabled: !!(packageId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPackageApiPackagesPackageIdGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>>
export type GetPackageApiPackagesPackageIdGetInfiniteQueryError = HTTPValidationError


export function useGetPackageApiPackagesPackageIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>>, TError = HTTPValidationError>(
 packageId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPackageApiPackagesPackageIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPackageApiPackagesPackageIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Package
 */

export function useGetPackageApiPackagesPackageIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetPackageApiPackagesPackageIdGetInfiniteQueryOptions(packageId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetPackageApiPackagesPackageIdGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(packageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPackageApiPackagesPackageIdGetQueryKey(packageId);

  const getPackageApiPackagesPackageIdGet =  useGetPackageApiPackagesPackageIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>> = ({ signal }) => getPackageApiPackagesPackageIdGet(packageId, signal);





   return  { queryKey, queryFn, enabled: !!(packageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPackageApiPackagesPackageIdGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>>
export type GetPackageApiPackagesPackageIdGetQueryError = HTTPValidationError


export function useGetPackageApiPackagesPackageIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(
 packageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPackageApiPackagesPackageIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPackageApiPackagesPackageIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Package
 */

export function useGetPackageApiPackagesPackageIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetPackageApiPackagesPackageIdGetQueryOptions(packageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetPackageApiPackagesPackageIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(packageId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPackageApiPackagesPackageIdGetQueryKey(packageId);

  const getPackageApiPackagesPackageIdGet =  useGetPackageApiPackagesPackageIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>> = ({ signal }) => getPackageApiPackagesPackageIdGet(packageId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPackageApiPackagesPackageIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>>
export type GetPackageApiPackagesPackageIdGetSuspenseQueryError = HTTPValidationError


export function useGetPackageApiPackagesPackageIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(
 packageId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPackageApiPackagesPackageIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPackageApiPackagesPackageIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Package
 */

export function useGetPackageApiPackagesPackageIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError = HTTPValidationError>(
 packageId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPackageApiPackagesPackageIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetPackageApiPackagesPackageIdGetSuspenseQueryOptions(packageId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Send Package
 */
export const useSendPackageApiPackagesPackageIdSendPostHook = () => {
        const sendPackageApiPackagesPackageIdSendPost = useCustomInstance<PackageResponse>();

        return useCallback((
    packageId: string,
    packageSendBodyNull: PackageSendBody | null,
 signal?: AbortSignal
) => {
        return sendPackageApiPackagesPackageIdSendPost(
          {url: `/api/packages/${packageId}/send`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: packageSendBodyNull, signal
    },
          );
        }, [sendPackageApiPackagesPackageIdSendPost])
      }



export const useSendPackageApiPackagesPackageIdSendPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSendPackageApiPackagesPackageIdSendPostHook>>>, TError,{packageId: string;data: PackageSendBody | null}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSendPackageApiPackagesPackageIdSendPostHook>>>, TError,{packageId: string;data: PackageSendBody | null}, TContext> => {

const mutationKey = ['sendPackageApiPackagesPackageIdSendPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const sendPackageApiPackagesPackageIdSendPost =  useSendPackageApiPackagesPackageIdSendPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useSendPackageApiPackagesPackageIdSendPostHook>>>, {packageId: string;data: PackageSendBody | null}> = (props) => {
          const {packageId,data} = props ?? {};

          return  sendPackageApiPackagesPackageIdSendPost(packageId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendPackageApiPackagesPackageIdSendPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSendPackageApiPackagesPackageIdSendPostHook>>>>
    export type SendPackageApiPackagesPackageIdSendPostMutationBody = PackageSendBody | null
    export type SendPackageApiPackagesPackageIdSendPostMutationError = HTTPValidationError

    /**
 * @summary Send Package
 */
export const useSendPackageApiPackagesPackageIdSendPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSendPackageApiPackagesPackageIdSendPostHook>>>, TError,{packageId: string;data: PackageSendBody | null}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useSendPackageApiPackagesPackageIdSendPostHook>>>,
        TError,
        {packageId: string;data: PackageSendBody | null},
        TContext
      > => {
      return useMutation(useSendPackageApiPackagesPackageIdSendPostMutationOptions(options), queryClient);
    }
    /**
 * @summary List Posts
 */
export const useListPostsApiChannelsChannelIdPostsGetHook = () => {
        const listPostsApiChannelsChannelIdPostsGet = useCustomInstance<PostResponse[]>();

        return useCallback((
    channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams,
 signal?: AbortSignal
) => {
        return listPostsApiChannelsChannelIdPostsGet(
          {url: `/api/channels/${channelId}/posts`, method: 'GET',
        params, signal
    },
          );
        }, [listPostsApiChannelsChannelIdPostsGet])
      }




export const getListPostsApiChannelsChannelIdPostsGetInfiniteQueryKey = (channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams,) => {
    return [
    'infinite', `/api/channels/${channelId}/posts`, ...(params ? [params] : [])
    ] as const;
    }

export const getListPostsApiChannelsChannelIdPostsGetQueryKey = (channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams,) => {
    return [
    `/api/channels/${channelId}/posts`, ...(params ? [params] : [])
    ] as const;
    }


export const useListPostsApiChannelsChannelIdPostsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>>, TError = HTTPValidationError>(channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostsApiChannelsChannelIdPostsGetInfiniteQueryKey(channelId,params);

  const listPostsApiChannelsChannelIdPostsGet =  useListPostsApiChannelsChannelIdPostsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>> = ({ signal }) => listPostsApiChannelsChannelIdPostsGet(channelId,params, signal);





   return  { queryKey, queryFn, enabled: !!(channelId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostsApiChannelsChannelIdPostsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>>
export type ListPostsApiChannelsChannelIdPostsGetInfiniteQueryError = HTTPValidationError


export function useListPostsApiChannelsChannelIdPostsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>>, TError = HTTPValidationError>(
 channelId: string,
    params: undefined |  ListPostsApiChannelsChannelIdPostsGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostsApiChannelsChannelIdPostsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostsApiChannelsChannelIdPostsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Posts
 */

export function useListPostsApiChannelsChannelIdPostsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostsApiChannelsChannelIdPostsGetInfiniteQueryOptions(channelId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListPostsApiChannelsChannelIdPostsGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostsApiChannelsChannelIdPostsGetQueryKey(channelId,params);

  const listPostsApiChannelsChannelIdPostsGet =  useListPostsApiChannelsChannelIdPostsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>> = ({ signal }) => listPostsApiChannelsChannelIdPostsGet(channelId,params, signal);





   return  { queryKey, queryFn, enabled: !!(channelId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostsApiChannelsChannelIdPostsGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>>
export type ListPostsApiChannelsChannelIdPostsGetQueryError = HTTPValidationError


export function useListPostsApiChannelsChannelIdPostsGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(
 channelId: string,
    params: undefined |  ListPostsApiChannelsChannelIdPostsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostsApiChannelsChannelIdPostsGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostsApiChannelsChannelIdPostsGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Posts
 */

export function useListPostsApiChannelsChannelIdPostsGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostsApiChannelsChannelIdPostsGetQueryOptions(channelId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListPostsApiChannelsChannelIdPostsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostsApiChannelsChannelIdPostsGetQueryKey(channelId,params);

  const listPostsApiChannelsChannelIdPostsGet =  useListPostsApiChannelsChannelIdPostsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>> = ({ signal }) => listPostsApiChannelsChannelIdPostsGet(channelId,params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostsApiChannelsChannelIdPostsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>>
export type ListPostsApiChannelsChannelIdPostsGetSuspenseQueryError = HTTPValidationError


export function useListPostsApiChannelsChannelIdPostsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(
 channelId: string,
    params: undefined |  ListPostsApiChannelsChannelIdPostsGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostsApiChannelsChannelIdPostsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostsApiChannelsChannelIdPostsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Posts
 */

export function useListPostsApiChannelsChannelIdPostsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError = HTTPValidationError>(
 channelId: string,
    params?: ListPostsApiChannelsChannelIdPostsGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostsApiChannelsChannelIdPostsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostsApiChannelsChannelIdPostsGetSuspenseQueryOptions(channelId,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Post
 */
export const useGetPostApiPostsPostIdGetHook = () => {
        const getPostApiPostsPostIdGet = useCustomInstance<PostResponse>();

        return useCallback((
    postId: string,
 signal?: AbortSignal
) => {
        return getPostApiPostsPostIdGet(
          {url: `/api/posts/${postId}`, method: 'GET', signal
    },
          );
        }, [getPostApiPostsPostIdGet])
      }




export const getGetPostApiPostsPostIdGetInfiniteQueryKey = (postId: string,) => {
    return [
    'infinite', `/api/posts/${postId}`
    ] as const;
    }

export const getGetPostApiPostsPostIdGetQueryKey = (postId: string,) => {
    return [
    `/api/posts/${postId}`
    ] as const;
    }


export const useGetPostApiPostsPostIdGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostApiPostsPostIdGetInfiniteQueryKey(postId);

  const getPostApiPostsPostIdGet =  useGetPostApiPostsPostIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>> = ({ signal }) => getPostApiPostsPostIdGet(postId, signal);





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostApiPostsPostIdGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>>
export type GetPostApiPostsPostIdGetInfiniteQueryError = HTTPValidationError


export function useGetPostApiPostsPostIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostApiPostsPostIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostApiPostsPostIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Post
 */

export function useGetPostApiPostsPostIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetPostApiPostsPostIdGetInfiniteQueryOptions(postId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetPostApiPostsPostIdGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostApiPostsPostIdGetQueryKey(postId);

  const getPostApiPostsPostIdGet =  useGetPostApiPostsPostIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>> = ({ signal }) => getPostApiPostsPostIdGet(postId, signal);





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostApiPostsPostIdGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>>
export type GetPostApiPostsPostIdGetQueryError = HTTPValidationError


export function useGetPostApiPostsPostIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostApiPostsPostIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostApiPostsPostIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Post
 */

export function useGetPostApiPostsPostIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetPostApiPostsPostIdGetQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetPostApiPostsPostIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostApiPostsPostIdGetQueryKey(postId);

  const getPostApiPostsPostIdGet =  useGetPostApiPostsPostIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>> = ({ signal }) => getPostApiPostsPostIdGet(postId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostApiPostsPostIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>>
export type GetPostApiPostsPostIdGetSuspenseQueryError = HTTPValidationError


export function useGetPostApiPostsPostIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostApiPostsPostIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostApiPostsPostIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Post
 */

export function useGetPostApiPostsPostIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPostApiPostsPostIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetPostApiPostsPostIdGetSuspenseQueryOptions(postId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List Post History
 */
export const useListPostHistoryApiPostsPostIdHistoryGetHook = () => {
        const listPostHistoryApiPostsPostIdHistoryGet = useCustomInstance<PostHistoryEntry[]>();

        return useCallback((
    postId: string,
 signal?: AbortSignal
) => {
        return listPostHistoryApiPostsPostIdHistoryGet(
          {url: `/api/posts/${postId}/history`, method: 'GET', signal
    },
          );
        }, [listPostHistoryApiPostsPostIdHistoryGet])
      }




export const getListPostHistoryApiPostsPostIdHistoryGetInfiniteQueryKey = (postId: string,) => {
    return [
    'infinite', `/api/posts/${postId}/history`
    ] as const;
    }

export const getListPostHistoryApiPostsPostIdHistoryGetQueryKey = (postId: string,) => {
    return [
    `/api/posts/${postId}/history`
    ] as const;
    }


export const useListPostHistoryApiPostsPostIdHistoryGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostHistoryApiPostsPostIdHistoryGetInfiniteQueryKey(postId);

  const listPostHistoryApiPostsPostIdHistoryGet =  useListPostHistoryApiPostsPostIdHistoryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>> = ({ signal }) => listPostHistoryApiPostsPostIdHistoryGet(postId, signal);





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostHistoryApiPostsPostIdHistoryGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>>
export type ListPostHistoryApiPostsPostIdHistoryGetInfiniteQueryError = HTTPValidationError


export function useListPostHistoryApiPostsPostIdHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostHistoryApiPostsPostIdHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostHistoryApiPostsPostIdHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Post History
 */

export function useListPostHistoryApiPostsPostIdHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostHistoryApiPostsPostIdHistoryGetInfiniteQueryOptions(postId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListPostHistoryApiPostsPostIdHistoryGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostHistoryApiPostsPostIdHistoryGetQueryKey(postId);

  const listPostHistoryApiPostsPostIdHistoryGet =  useListPostHistoryApiPostsPostIdHistoryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>> = ({ signal }) => listPostHistoryApiPostsPostIdHistoryGet(postId, signal);





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostHistoryApiPostsPostIdHistoryGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>>
export type ListPostHistoryApiPostsPostIdHistoryGetQueryError = HTTPValidationError


export function useListPostHistoryApiPostsPostIdHistoryGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostHistoryApiPostsPostIdHistoryGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostHistoryApiPostsPostIdHistoryGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Post History
 */

export function useListPostHistoryApiPostsPostIdHistoryGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostHistoryApiPostsPostIdHistoryGetQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListPostHistoryApiPostsPostIdHistoryGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostHistoryApiPostsPostIdHistoryGetQueryKey(postId);

  const listPostHistoryApiPostsPostIdHistoryGet =  useListPostHistoryApiPostsPostIdHistoryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>> = ({ signal }) => listPostHistoryApiPostsPostIdHistoryGet(postId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostHistoryApiPostsPostIdHistoryGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>>
export type ListPostHistoryApiPostsPostIdHistoryGetSuspenseQueryError = HTTPValidationError


export function useListPostHistoryApiPostsPostIdHistoryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostHistoryApiPostsPostIdHistoryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostHistoryApiPostsPostIdHistoryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Post History
 */

export function useListPostHistoryApiPostsPostIdHistoryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostHistoryApiPostsPostIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostHistoryApiPostsPostIdHistoryGetSuspenseQueryOptions(postId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary List Post Sources
 */
export const useListPostSourcesApiPostsPostIdSourcesGetHook = () => {
        const listPostSourcesApiPostsPostIdSourcesGet = useCustomInstance<PostSourcesResponse>();

        return useCallback((
    postId: string,
 signal?: AbortSignal
) => {
        return listPostSourcesApiPostsPostIdSourcesGet(
          {url: `/api/posts/${postId}/sources`, method: 'GET', signal
    },
          );
        }, [listPostSourcesApiPostsPostIdSourcesGet])
      }




export const getListPostSourcesApiPostsPostIdSourcesGetInfiniteQueryKey = (postId: string,) => {
    return [
    'infinite', `/api/posts/${postId}/sources`
    ] as const;
    }

export const getListPostSourcesApiPostsPostIdSourcesGetQueryKey = (postId: string,) => {
    return [
    `/api/posts/${postId}/sources`
    ] as const;
    }


export const useListPostSourcesApiPostsPostIdSourcesGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostSourcesApiPostsPostIdSourcesGetInfiniteQueryKey(postId);

  const listPostSourcesApiPostsPostIdSourcesGet =  useListPostSourcesApiPostsPostIdSourcesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>> = ({ signal }) => listPostSourcesApiPostsPostIdSourcesGet(postId, signal);





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostSourcesApiPostsPostIdSourcesGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>>
export type ListPostSourcesApiPostsPostIdSourcesGetInfiniteQueryError = HTTPValidationError


export function useListPostSourcesApiPostsPostIdSourcesGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostSourcesApiPostsPostIdSourcesGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostSourcesApiPostsPostIdSourcesGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Post Sources
 */

export function useListPostSourcesApiPostsPostIdSourcesGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostSourcesApiPostsPostIdSourcesGetInfiniteQueryOptions(postId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListPostSourcesApiPostsPostIdSourcesGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostSourcesApiPostsPostIdSourcesGetQueryKey(postId);

  const listPostSourcesApiPostsPostIdSourcesGet =  useListPostSourcesApiPostsPostIdSourcesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>> = ({ signal }) => listPostSourcesApiPostsPostIdSourcesGet(postId, signal);





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostSourcesApiPostsPostIdSourcesGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>>
export type ListPostSourcesApiPostsPostIdSourcesGetQueryError = HTTPValidationError


export function useListPostSourcesApiPostsPostIdSourcesGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostSourcesApiPostsPostIdSourcesGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostSourcesApiPostsPostIdSourcesGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Post Sources
 */

export function useListPostSourcesApiPostsPostIdSourcesGet<TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostSourcesApiPostsPostIdSourcesGetQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListPostSourcesApiPostsPostIdSourcesGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostSourcesApiPostsPostIdSourcesGetQueryKey(postId);

  const listPostSourcesApiPostsPostIdSourcesGet =  useListPostSourcesApiPostsPostIdSourcesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>> = ({ signal }) => listPostSourcesApiPostsPostIdSourcesGet(postId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPostSourcesApiPostsPostIdSourcesGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>>
export type ListPostSourcesApiPostsPostIdSourcesGetSuspenseQueryError = HTTPValidationError


export function useListPostSourcesApiPostsPostIdSourcesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostSourcesApiPostsPostIdSourcesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPostSourcesApiPostsPostIdSourcesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Post Sources
 */

export function useListPostSourcesApiPostsPostIdSourcesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListPostSourcesApiPostsPostIdSourcesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListPostSourcesApiPostsPostIdSourcesGetSuspenseQueryOptions(postId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Mark Post Read
 */
export const useMarkPostReadApiPostsPostIdReadPostHook = () => {
        const markPostReadApiPostsPostIdReadPost = useCustomInstance<PostResponse>();

        return useCallback((
    postId: string,
 signal?: AbortSignal
) => {
        return markPostReadApiPostsPostIdReadPost(
          {url: `/api/posts/${postId}/read`, method: 'POST', signal
    },
          );
        }, [markPostReadApiPostsPostIdReadPost])
      }



export const useMarkPostReadApiPostsPostIdReadPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useMarkPostReadApiPostsPostIdReadPostHook>>>, TError,{postId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useMarkPostReadApiPostsPostIdReadPostHook>>>, TError,{postId: string}, TContext> => {

const mutationKey = ['markPostReadApiPostsPostIdReadPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const markPostReadApiPostsPostIdReadPost =  useMarkPostReadApiPostsPostIdReadPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useMarkPostReadApiPostsPostIdReadPostHook>>>, {postId: string}> = (props) => {
          const {postId} = props ?? {};

          return  markPostReadApiPostsPostIdReadPost(postId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkPostReadApiPostsPostIdReadPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useMarkPostReadApiPostsPostIdReadPostHook>>>>

    export type MarkPostReadApiPostsPostIdReadPostMutationError = HTTPValidationError

    /**
 * @summary Mark Post Read
 */
export const useMarkPostReadApiPostsPostIdReadPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useMarkPostReadApiPostsPostIdReadPostHook>>>, TError,{postId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useMarkPostReadApiPostsPostIdReadPostHook>>>,
        TError,
        {postId: string},
        TContext
      > => {
      return useMutation(useMarkPostReadApiPostsPostIdReadPostMutationOptions(options), queryClient);
    }
