/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  CommentCreate,
  CommentResponse,
  HTTPValidationError,
  ReviewActionCreate,
  ReviewActionResponse,
  SuggestionCreate,
  SuggestionRespond,
  SuggestionResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * @summary List Suggestions
 */
export const useListSuggestionsApiTeamsTeamIdSuggestionsGetHook = () => {
        const listSuggestionsApiTeamsTeamIdSuggestionsGet = useCustomInstance<SuggestionResponse[]>();

        return useCallback((
    teamId: string,
 signal?: AbortSignal
) => {
        return listSuggestionsApiTeamsTeamIdSuggestionsGet(
          {url: `/api/teams/${teamId}/suggestions`, method: 'GET', signal
    },
          );
        }, [listSuggestionsApiTeamsTeamIdSuggestionsGet])
      }




export const getListSuggestionsApiTeamsTeamIdSuggestionsGetInfiniteQueryKey = (teamId: string,) => {
    return [
    'infinite', `/api/teams/${teamId}/suggestions`
    ] as const;
    }

export const getListSuggestionsApiTeamsTeamIdSuggestionsGetQueryKey = (teamId: string,) => {
    return [
    `/api/teams/${teamId}/suggestions`
    ] as const;
    }


export const useListSuggestionsApiTeamsTeamIdSuggestionsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSuggestionsApiTeamsTeamIdSuggestionsGetInfiniteQueryKey(teamId);

  const listSuggestionsApiTeamsTeamIdSuggestionsGet =  useListSuggestionsApiTeamsTeamIdSuggestionsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>> = ({ signal }) => listSuggestionsApiTeamsTeamIdSuggestionsGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSuggestionsApiTeamsTeamIdSuggestionsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>>
export type ListSuggestionsApiTeamsTeamIdSuggestionsGetInfiniteQueryError = HTTPValidationError


export function useListSuggestionsApiTeamsTeamIdSuggestionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSuggestionsApiTeamsTeamIdSuggestionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSuggestionsApiTeamsTeamIdSuggestionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Suggestions
 */

export function useListSuggestionsApiTeamsTeamIdSuggestionsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListSuggestionsApiTeamsTeamIdSuggestionsGetInfiniteQueryOptions(teamId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListSuggestionsApiTeamsTeamIdSuggestionsGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSuggestionsApiTeamsTeamIdSuggestionsGetQueryKey(teamId);

  const listSuggestionsApiTeamsTeamIdSuggestionsGet =  useListSuggestionsApiTeamsTeamIdSuggestionsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>> = ({ signal }) => listSuggestionsApiTeamsTeamIdSuggestionsGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSuggestionsApiTeamsTeamIdSuggestionsGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>>
export type ListSuggestionsApiTeamsTeamIdSuggestionsGetQueryError = HTTPValidationError


export function useListSuggestionsApiTeamsTeamIdSuggestionsGet<TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSuggestionsApiTeamsTeamIdSuggestionsGet<TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSuggestionsApiTeamsTeamIdSuggestionsGet<TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Suggestions
 */

export function useListSuggestionsApiTeamsTeamIdSuggestionsGet<TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListSuggestionsApiTeamsTeamIdSuggestionsGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListSuggestionsApiTeamsTeamIdSuggestionsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSuggestionsApiTeamsTeamIdSuggestionsGetQueryKey(teamId);

  const listSuggestionsApiTeamsTeamIdSuggestionsGet =  useListSuggestionsApiTeamsTeamIdSuggestionsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>> = ({ signal }) => listSuggestionsApiTeamsTeamIdSuggestionsGet(teamId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSuggestionsApiTeamsTeamIdSuggestionsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>>
export type ListSuggestionsApiTeamsTeamIdSuggestionsGetSuspenseQueryError = HTTPValidationError


export function useListSuggestionsApiTeamsTeamIdSuggestionsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSuggestionsApiTeamsTeamIdSuggestionsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSuggestionsApiTeamsTeamIdSuggestionsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Suggestions
 */

export function useListSuggestionsApiTeamsTeamIdSuggestionsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListSuggestionsApiTeamsTeamIdSuggestionsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListSuggestionsApiTeamsTeamIdSuggestionsGetSuspenseQueryOptions(teamId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Suggestion
 */
export const useCreateSuggestionApiPostsPostIdSuggestionsPostHook = () => {
        const createSuggestionApiPostsPostIdSuggestionsPost = useCustomInstance<SuggestionResponse>();

        return useCallback((
    postId: string,
    suggestionCreate: SuggestionCreate,
 signal?: AbortSignal
) => {
        return createSuggestionApiPostsPostIdSuggestionsPost(
          {url: `/api/posts/${postId}/suggestions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: suggestionCreate, signal
    },
          );
        }, [createSuggestionApiPostsPostIdSuggestionsPost])
      }



export const useCreateSuggestionApiPostsPostIdSuggestionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateSuggestionApiPostsPostIdSuggestionsPostHook>>>, TError,{postId: string;data: SuggestionCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateSuggestionApiPostsPostIdSuggestionsPostHook>>>, TError,{postId: string;data: SuggestionCreate}, TContext> => {

const mutationKey = ['createSuggestionApiPostsPostIdSuggestionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createSuggestionApiPostsPostIdSuggestionsPost =  useCreateSuggestionApiPostsPostIdSuggestionsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateSuggestionApiPostsPostIdSuggestionsPostHook>>>, {postId: string;data: SuggestionCreate}> = (props) => {
          const {postId,data} = props ?? {};

          return  createSuggestionApiPostsPostIdSuggestionsPost(postId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSuggestionApiPostsPostIdSuggestionsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateSuggestionApiPostsPostIdSuggestionsPostHook>>>>
    export type CreateSuggestionApiPostsPostIdSuggestionsPostMutationBody = SuggestionCreate
    export type CreateSuggestionApiPostsPostIdSuggestionsPostMutationError = HTTPValidationError

    /**
 * @summary Create Suggestion
 */
export const useCreateSuggestionApiPostsPostIdSuggestionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateSuggestionApiPostsPostIdSuggestionsPostHook>>>, TError,{postId: string;data: SuggestionCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateSuggestionApiPostsPostIdSuggestionsPostHook>>>,
        TError,
        {postId: string;data: SuggestionCreate},
        TContext
      > => {
      return useMutation(useCreateSuggestionApiPostsPostIdSuggestionsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Respond Suggestion
 */
export const useRespondSuggestionApiSuggestionsSuggestionIdRespondPostHook = () => {
        const respondSuggestionApiSuggestionsSuggestionIdRespondPost = useCustomInstance<SuggestionResponse>();

        return useCallback((
    suggestionId: string,
    suggestionRespond: SuggestionRespond,
 signal?: AbortSignal
) => {
        return respondSuggestionApiSuggestionsSuggestionIdRespondPost(
          {url: `/api/suggestions/${suggestionId}/respond`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: suggestionRespond, signal
    },
          );
        }, [respondSuggestionApiSuggestionsSuggestionIdRespondPost])
      }



export const useRespondSuggestionApiSuggestionsSuggestionIdRespondPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRespondSuggestionApiSuggestionsSuggestionIdRespondPostHook>>>, TError,{suggestionId: string;data: SuggestionRespond}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRespondSuggestionApiSuggestionsSuggestionIdRespondPostHook>>>, TError,{suggestionId: string;data: SuggestionRespond}, TContext> => {

const mutationKey = ['respondSuggestionApiSuggestionsSuggestionIdRespondPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const respondSuggestionApiSuggestionsSuggestionIdRespondPost =  useRespondSuggestionApiSuggestionsSuggestionIdRespondPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRespondSuggestionApiSuggestionsSuggestionIdRespondPostHook>>>, {suggestionId: string;data: SuggestionRespond}> = (props) => {
          const {suggestionId,data} = props ?? {};

          return  respondSuggestionApiSuggestionsSuggestionIdRespondPost(suggestionId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RespondSuggestionApiSuggestionsSuggestionIdRespondPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRespondSuggestionApiSuggestionsSuggestionIdRespondPostHook>>>>
    export type RespondSuggestionApiSuggestionsSuggestionIdRespondPostMutationBody = SuggestionRespond
    export type RespondSuggestionApiSuggestionsSuggestionIdRespondPostMutationError = HTTPValidationError

    /**
 * @summary Respond Suggestion
 */
export const useRespondSuggestionApiSuggestionsSuggestionIdRespondPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRespondSuggestionApiSuggestionsSuggestionIdRespondPostHook>>>, TError,{suggestionId: string;data: SuggestionRespond}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRespondSuggestionApiSuggestionsSuggestionIdRespondPostHook>>>,
        TError,
        {suggestionId: string;data: SuggestionRespond},
        TContext
      > => {
      return useMutation(useRespondSuggestionApiSuggestionsSuggestionIdRespondPostMutationOptions(options), queryClient);
    }
    /**
 * Record this team's approval; applies when both teams have approved.
 * @summary Approve Suggestion
 */
export const useApproveSuggestionApiSuggestionsSuggestionIdApprovePostHook = () => {
        const approveSuggestionApiSuggestionsSuggestionIdApprovePost = useCustomInstance<SuggestionResponse>();

        return useCallback((
    suggestionId: string,
 signal?: AbortSignal
) => {
        return approveSuggestionApiSuggestionsSuggestionIdApprovePost(
          {url: `/api/suggestions/${suggestionId}/approve`, method: 'POST', signal
    },
          );
        }, [approveSuggestionApiSuggestionsSuggestionIdApprovePost])
      }



export const useApproveSuggestionApiSuggestionsSuggestionIdApprovePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useApproveSuggestionApiSuggestionsSuggestionIdApprovePostHook>>>, TError,{suggestionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useApproveSuggestionApiSuggestionsSuggestionIdApprovePostHook>>>, TError,{suggestionId: string}, TContext> => {

const mutationKey = ['approveSuggestionApiSuggestionsSuggestionIdApprovePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const approveSuggestionApiSuggestionsSuggestionIdApprovePost =  useApproveSuggestionApiSuggestionsSuggestionIdApprovePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useApproveSuggestionApiSuggestionsSuggestionIdApprovePostHook>>>, {suggestionId: string}> = (props) => {
          const {suggestionId} = props ?? {};

          return  approveSuggestionApiSuggestionsSuggestionIdApprovePost(suggestionId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApproveSuggestionApiSuggestionsSuggestionIdApprovePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useApproveSuggestionApiSuggestionsSuggestionIdApprovePostHook>>>>

    export type ApproveSuggestionApiSuggestionsSuggestionIdApprovePostMutationError = HTTPValidationError

    /**
 * @summary Approve Suggestion
 */
export const useApproveSuggestionApiSuggestionsSuggestionIdApprovePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useApproveSuggestionApiSuggestionsSuggestionIdApprovePostHook>>>, TError,{suggestionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useApproveSuggestionApiSuggestionsSuggestionIdApprovePostHook>>>,
        TError,
        {suggestionId: string},
        TContext
      > => {
      return useMutation(useApproveSuggestionApiSuggestionsSuggestionIdApprovePostMutationOptions(options), queryClient);
    }
    /**
 * Proposer withdraws the edit request (open or awaiting approvals only).
 * @summary Cancel Suggestion
 */
export const useCancelSuggestionApiSuggestionsSuggestionIdCancelPostHook = () => {
        const cancelSuggestionApiSuggestionsSuggestionIdCancelPost = useCustomInstance<SuggestionResponse>();

        return useCallback((
    suggestionId: string,
 signal?: AbortSignal
) => {
        return cancelSuggestionApiSuggestionsSuggestionIdCancelPost(
          {url: `/api/suggestions/${suggestionId}/cancel`, method: 'POST', signal
    },
          );
        }, [cancelSuggestionApiSuggestionsSuggestionIdCancelPost])
      }



export const useCancelSuggestionApiSuggestionsSuggestionIdCancelPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCancelSuggestionApiSuggestionsSuggestionIdCancelPostHook>>>, TError,{suggestionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCancelSuggestionApiSuggestionsSuggestionIdCancelPostHook>>>, TError,{suggestionId: string}, TContext> => {

const mutationKey = ['cancelSuggestionApiSuggestionsSuggestionIdCancelPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const cancelSuggestionApiSuggestionsSuggestionIdCancelPost =  useCancelSuggestionApiSuggestionsSuggestionIdCancelPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCancelSuggestionApiSuggestionsSuggestionIdCancelPostHook>>>, {suggestionId: string}> = (props) => {
          const {suggestionId} = props ?? {};

          return  cancelSuggestionApiSuggestionsSuggestionIdCancelPost(suggestionId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CancelSuggestionApiSuggestionsSuggestionIdCancelPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCancelSuggestionApiSuggestionsSuggestionIdCancelPostHook>>>>

    export type CancelSuggestionApiSuggestionsSuggestionIdCancelPostMutationError = HTTPValidationError

    /**
 * @summary Cancel Suggestion
 */
export const useCancelSuggestionApiSuggestionsSuggestionIdCancelPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCancelSuggestionApiSuggestionsSuggestionIdCancelPostHook>>>, TError,{suggestionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCancelSuggestionApiSuggestionsSuggestionIdCancelPostHook>>>,
        TError,
        {suggestionId: string},
        TContext
      > => {
      return useMutation(useCancelSuggestionApiSuggestionsSuggestionIdCancelPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Close Suggestion
 */
export const useCloseSuggestionApiSuggestionsSuggestionIdClosePostHook = () => {
        const closeSuggestionApiSuggestionsSuggestionIdClosePost = useCustomInstance<SuggestionResponse>();

        return useCallback((
    suggestionId: string,
 signal?: AbortSignal
) => {
        return closeSuggestionApiSuggestionsSuggestionIdClosePost(
          {url: `/api/suggestions/${suggestionId}/close`, method: 'POST', signal
    },
          );
        }, [closeSuggestionApiSuggestionsSuggestionIdClosePost])
      }



export const useCloseSuggestionApiSuggestionsSuggestionIdClosePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCloseSuggestionApiSuggestionsSuggestionIdClosePostHook>>>, TError,{suggestionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCloseSuggestionApiSuggestionsSuggestionIdClosePostHook>>>, TError,{suggestionId: string}, TContext> => {

const mutationKey = ['closeSuggestionApiSuggestionsSuggestionIdClosePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const closeSuggestionApiSuggestionsSuggestionIdClosePost =  useCloseSuggestionApiSuggestionsSuggestionIdClosePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCloseSuggestionApiSuggestionsSuggestionIdClosePostHook>>>, {suggestionId: string}> = (props) => {
          const {suggestionId} = props ?? {};

          return  closeSuggestionApiSuggestionsSuggestionIdClosePost(suggestionId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CloseSuggestionApiSuggestionsSuggestionIdClosePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCloseSuggestionApiSuggestionsSuggestionIdClosePostHook>>>>

    export type CloseSuggestionApiSuggestionsSuggestionIdClosePostMutationError = HTTPValidationError

    /**
 * @summary Close Suggestion
 */
export const useCloseSuggestionApiSuggestionsSuggestionIdClosePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCloseSuggestionApiSuggestionsSuggestionIdClosePostHook>>>, TError,{suggestionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCloseSuggestionApiSuggestionsSuggestionIdClosePostHook>>>,
        TError,
        {suggestionId: string},
        TContext
      > => {
      return useMutation(useCloseSuggestionApiSuggestionsSuggestionIdClosePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Create Review Action
 */
export const useCreateReviewActionApiPostsPostIdReviewActionsPostHook = () => {
        const createReviewActionApiPostsPostIdReviewActionsPost = useCustomInstance<ReviewActionResponse>();

        return useCallback((
    postId: string,
    reviewActionCreate: ReviewActionCreate,
 signal?: AbortSignal
) => {
        return createReviewActionApiPostsPostIdReviewActionsPost(
          {url: `/api/posts/${postId}/review-actions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reviewActionCreate, signal
    },
          );
        }, [createReviewActionApiPostsPostIdReviewActionsPost])
      }



export const useCreateReviewActionApiPostsPostIdReviewActionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateReviewActionApiPostsPostIdReviewActionsPostHook>>>, TError,{postId: string;data: ReviewActionCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateReviewActionApiPostsPostIdReviewActionsPostHook>>>, TError,{postId: string;data: ReviewActionCreate}, TContext> => {

const mutationKey = ['createReviewActionApiPostsPostIdReviewActionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createReviewActionApiPostsPostIdReviewActionsPost =  useCreateReviewActionApiPostsPostIdReviewActionsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateReviewActionApiPostsPostIdReviewActionsPostHook>>>, {postId: string;data: ReviewActionCreate}> = (props) => {
          const {postId,data} = props ?? {};

          return  createReviewActionApiPostsPostIdReviewActionsPost(postId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateReviewActionApiPostsPostIdReviewActionsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateReviewActionApiPostsPostIdReviewActionsPostHook>>>>
    export type CreateReviewActionApiPostsPostIdReviewActionsPostMutationBody = ReviewActionCreate
    export type CreateReviewActionApiPostsPostIdReviewActionsPostMutationError = HTTPValidationError

    /**
 * @summary Create Review Action
 */
export const useCreateReviewActionApiPostsPostIdReviewActionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateReviewActionApiPostsPostIdReviewActionsPostHook>>>, TError,{postId: string;data: ReviewActionCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateReviewActionApiPostsPostIdReviewActionsPostHook>>>,
        TError,
        {postId: string;data: ReviewActionCreate},
        TContext
      > => {
      return useMutation(useCreateReviewActionApiPostsPostIdReviewActionsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Create Comment
 */
export const useCreateCommentApiPostsPostIdCommentsPostHook = () => {
        const createCommentApiPostsPostIdCommentsPost = useCustomInstance<CommentResponse>();

        return useCallback((
    postId: string,
    commentCreate: CommentCreate,
 signal?: AbortSignal
) => {
        return createCommentApiPostsPostIdCommentsPost(
          {url: `/api/posts/${postId}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commentCreate, signal
    },
          );
        }, [createCommentApiPostsPostIdCommentsPost])
      }



export const useCreateCommentApiPostsPostIdCommentsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateCommentApiPostsPostIdCommentsPostHook>>>, TError,{postId: string;data: CommentCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateCommentApiPostsPostIdCommentsPostHook>>>, TError,{postId: string;data: CommentCreate}, TContext> => {

const mutationKey = ['createCommentApiPostsPostIdCommentsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createCommentApiPostsPostIdCommentsPost =  useCreateCommentApiPostsPostIdCommentsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateCommentApiPostsPostIdCommentsPostHook>>>, {postId: string;data: CommentCreate}> = (props) => {
          const {postId,data} = props ?? {};

          return  createCommentApiPostsPostIdCommentsPost(postId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCommentApiPostsPostIdCommentsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateCommentApiPostsPostIdCommentsPostHook>>>>
    export type CreateCommentApiPostsPostIdCommentsPostMutationBody = CommentCreate
    export type CreateCommentApiPostsPostIdCommentsPostMutationError = HTTPValidationError

    /**
 * @summary Create Comment
 */
export const useCreateCommentApiPostsPostIdCommentsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateCommentApiPostsPostIdCommentsPostHook>>>, TError,{postId: string;data: CommentCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateCommentApiPostsPostIdCommentsPostHook>>>,
        TError,
        {postId: string;data: CommentCreate},
        TContext
      > => {
      return useMutation(useCreateCommentApiPostsPostIdCommentsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary List Comments
 */
export const useListCommentsApiPostsPostIdCommentsGetHook = () => {
        const listCommentsApiPostsPostIdCommentsGet = useCustomInstance<CommentResponse[]>();

        return useCallback((
    postId: string,
 signal?: AbortSignal
) => {
        return listCommentsApiPostsPostIdCommentsGet(
          {url: `/api/posts/${postId}/comments`, method: 'GET', signal
    },
          );
        }, [listCommentsApiPostsPostIdCommentsGet])
      }




export const getListCommentsApiPostsPostIdCommentsGetInfiniteQueryKey = (postId: string,) => {
    return [
    'infinite', `/api/posts/${postId}/comments`
    ] as const;
    }

export const getListCommentsApiPostsPostIdCommentsGetQueryKey = (postId: string,) => {
    return [
    `/api/posts/${postId}/comments`
    ] as const;
    }


export const useListCommentsApiPostsPostIdCommentsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsApiPostsPostIdCommentsGetInfiniteQueryKey(postId);

  const listCommentsApiPostsPostIdCommentsGet =  useListCommentsApiPostsPostIdCommentsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>> = ({ signal }) => listCommentsApiPostsPostIdCommentsGet(postId, signal);





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsApiPostsPostIdCommentsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>>
export type ListCommentsApiPostsPostIdCommentsGetInfiniteQueryError = HTTPValidationError


export function useListCommentsApiPostsPostIdCommentsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCommentsApiPostsPostIdCommentsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCommentsApiPostsPostIdCommentsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Comments
 */

export function useListCommentsApiPostsPostIdCommentsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListCommentsApiPostsPostIdCommentsGetInfiniteQueryOptions(postId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListCommentsApiPostsPostIdCommentsGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsApiPostsPostIdCommentsGetQueryKey(postId);

  const listCommentsApiPostsPostIdCommentsGet =  useListCommentsApiPostsPostIdCommentsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>> = ({ signal }) => listCommentsApiPostsPostIdCommentsGet(postId, signal);





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsApiPostsPostIdCommentsGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>>
export type ListCommentsApiPostsPostIdCommentsGetQueryError = HTTPValidationError


export function useListCommentsApiPostsPostIdCommentsGet<TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCommentsApiPostsPostIdCommentsGet<TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCommentsApiPostsPostIdCommentsGet<TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Comments
 */

export function useListCommentsApiPostsPostIdCommentsGet<TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListCommentsApiPostsPostIdCommentsGetQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListCommentsApiPostsPostIdCommentsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsApiPostsPostIdCommentsGetQueryKey(postId);

  const listCommentsApiPostsPostIdCommentsGet =  useListCommentsApiPostsPostIdCommentsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>> = ({ signal }) => listCommentsApiPostsPostIdCommentsGet(postId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListCommentsApiPostsPostIdCommentsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>>
export type ListCommentsApiPostsPostIdCommentsGetSuspenseQueryError = HTTPValidationError


export function useListCommentsApiPostsPostIdCommentsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(
 postId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCommentsApiPostsPostIdCommentsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListCommentsApiPostsPostIdCommentsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Comments
 */

export function useListCommentsApiPostsPostIdCommentsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError = HTTPValidationError>(
 postId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListCommentsApiPostsPostIdCommentsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListCommentsApiPostsPostIdCommentsGetSuspenseQueryOptions(postId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




