/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  BodyUploadDocumentApiTeamsTeamIdDocumentsPost,
  DocumentResponse,
  HTTPValidationError,
  PasteDocumentBody
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * @summary Upload Document
 */
export const useUploadDocumentApiTeamsTeamIdDocumentsPostHook = () => {
        const uploadDocumentApiTeamsTeamIdDocumentsPost = useCustomInstance<DocumentResponse>();

        return useCallback((
    teamId: string,
    bodyUploadDocumentApiTeamsTeamIdDocumentsPost: BodyUploadDocumentApiTeamsTeamIdDocumentsPost,
 signal?: AbortSignal
) => {const formData = new FormData();
formData.append(`file`, bodyUploadDocumentApiTeamsTeamIdDocumentsPost.file);

        return uploadDocumentApiTeamsTeamIdDocumentsPost(
          {url: `/api/teams/${teamId}/documents`, method: 'POST',
       data: formData, signal
    },
          );
        }, [uploadDocumentApiTeamsTeamIdDocumentsPost])
      }



export const useUploadDocumentApiTeamsTeamIdDocumentsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUploadDocumentApiTeamsTeamIdDocumentsPostHook>>>, TError,{teamId: string;data: BodyUploadDocumentApiTeamsTeamIdDocumentsPost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUploadDocumentApiTeamsTeamIdDocumentsPostHook>>>, TError,{teamId: string;data: BodyUploadDocumentApiTeamsTeamIdDocumentsPost}, TContext> => {

const mutationKey = ['uploadDocumentApiTeamsTeamIdDocumentsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const uploadDocumentApiTeamsTeamIdDocumentsPost =  useUploadDocumentApiTeamsTeamIdDocumentsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useUploadDocumentApiTeamsTeamIdDocumentsPostHook>>>, {teamId: string;data: BodyUploadDocumentApiTeamsTeamIdDocumentsPost}> = (props) => {
          const {teamId,data} = props ?? {};

          return  uploadDocumentApiTeamsTeamIdDocumentsPost(teamId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadDocumentApiTeamsTeamIdDocumentsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useUploadDocumentApiTeamsTeamIdDocumentsPostHook>>>>
    export type UploadDocumentApiTeamsTeamIdDocumentsPostMutationBody = BodyUploadDocumentApiTeamsTeamIdDocumentsPost
    export type UploadDocumentApiTeamsTeamIdDocumentsPostMutationError = HTTPValidationError

    /**
 * @summary Upload Document
 */
export const useUploadDocumentApiTeamsTeamIdDocumentsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUploadDocumentApiTeamsTeamIdDocumentsPostHook>>>, TError,{teamId: string;data: BodyUploadDocumentApiTeamsTeamIdDocumentsPost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useUploadDocumentApiTeamsTeamIdDocumentsPostHook>>>,
        TError,
        {teamId: string;data: BodyUploadDocumentApiTeamsTeamIdDocumentsPost},
        TContext
      > => {
      return useMutation(useUploadDocumentApiTeamsTeamIdDocumentsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Paste Document
 */
export const usePasteDocumentApiTeamsTeamIdDocumentsPastePostHook = () => {
        const pasteDocumentApiTeamsTeamIdDocumentsPastePost = useCustomInstance<DocumentResponse>();

        return useCallback((
    teamId: string,
    pasteDocumentBody: PasteDocumentBody,
 signal?: AbortSignal
) => {
        return pasteDocumentApiTeamsTeamIdDocumentsPastePost(
          {url: `/api/teams/${teamId}/documents/paste`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pasteDocumentBody, signal
    },
          );
        }, [pasteDocumentApiTeamsTeamIdDocumentsPastePost])
      }



export const usePasteDocumentApiTeamsTeamIdDocumentsPastePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasteDocumentApiTeamsTeamIdDocumentsPastePostHook>>>, TError,{teamId: string;data: PasteDocumentBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasteDocumentApiTeamsTeamIdDocumentsPastePostHook>>>, TError,{teamId: string;data: PasteDocumentBody}, TContext> => {

const mutationKey = ['pasteDocumentApiTeamsTeamIdDocumentsPastePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const pasteDocumentApiTeamsTeamIdDocumentsPastePost =  usePasteDocumentApiTeamsTeamIdDocumentsPastePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof usePasteDocumentApiTeamsTeamIdDocumentsPastePostHook>>>, {teamId: string;data: PasteDocumentBody}> = (props) => {
          const {teamId,data} = props ?? {};

          return  pasteDocumentApiTeamsTeamIdDocumentsPastePost(teamId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PasteDocumentApiTeamsTeamIdDocumentsPastePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof usePasteDocumentApiTeamsTeamIdDocumentsPastePostHook>>>>
    export type PasteDocumentApiTeamsTeamIdDocumentsPastePostMutationBody = PasteDocumentBody
    export type PasteDocumentApiTeamsTeamIdDocumentsPastePostMutationError = HTTPValidationError

    /**
 * @summary Paste Document
 */
export const usePasteDocumentApiTeamsTeamIdDocumentsPastePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasteDocumentApiTeamsTeamIdDocumentsPastePostHook>>>, TError,{teamId: string;data: PasteDocumentBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof usePasteDocumentApiTeamsTeamIdDocumentsPastePostHook>>>,
        TError,
        {teamId: string;data: PasteDocumentBody},
        TContext
      > => {
      return useMutation(usePasteDocumentApiTeamsTeamIdDocumentsPastePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Document
 */
export const useGetDocumentApiDocumentsDocumentIdGetHook = () => {
        const getDocumentApiDocumentsDocumentIdGet = useCustomInstance<DocumentResponse>();

        return useCallback((
    documentId: string,
 signal?: AbortSignal
) => {
        return getDocumentApiDocumentsDocumentIdGet(
          {url: `/api/documents/${documentId}`, method: 'GET', signal
    },
          );
        }, [getDocumentApiDocumentsDocumentIdGet])
      }




export const getGetDocumentApiDocumentsDocumentIdGetInfiniteQueryKey = (documentId: string,) => {
    return [
    'infinite', `/api/documents/${documentId}`
    ] as const;
    }

export const getGetDocumentApiDocumentsDocumentIdGetQueryKey = (documentId: string,) => {
    return [
    `/api/documents/${documentId}`
    ] as const;
    }


export const useGetDocumentApiDocumentsDocumentIdGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>>, TError = HTTPValidationError>(documentId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentApiDocumentsDocumentIdGetInfiniteQueryKey(documentId);

  const getDocumentApiDocumentsDocumentIdGet =  useGetDocumentApiDocumentsDocumentIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>> = ({ signal }) => getDocumentApiDocumentsDocumentIdGet(documentId, signal);





   return  { queryKey, queryFn, enabled: !!(documentId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentApiDocumentsDocumentIdGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>>
export type GetDocumentApiDocumentsDocumentIdGetInfiniteQueryError = HTTPValidationError


export function useGetDocumentApiDocumentsDocumentIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>>, TError = HTTPValidationError>(
 documentId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentApiDocumentsDocumentIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentApiDocumentsDocumentIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document
 */

export function useGetDocumentApiDocumentsDocumentIdGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetDocumentApiDocumentsDocumentIdGetInfiniteQueryOptions(documentId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetDocumentApiDocumentsDocumentIdGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentApiDocumentsDocumentIdGetQueryKey(documentId);

  const getDocumentApiDocumentsDocumentIdGet =  useGetDocumentApiDocumentsDocumentIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>> = ({ signal }) => getDocumentApiDocumentsDocumentIdGet(documentId, signal);





   return  { queryKey, queryFn, enabled: !!(documentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentApiDocumentsDocumentIdGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>>
export type GetDocumentApiDocumentsDocumentIdGetQueryError = HTTPValidationError


export function useGetDocumentApiDocumentsDocumentIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(
 documentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentApiDocumentsDocumentIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentApiDocumentsDocumentIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document
 */

export function useGetDocumentApiDocumentsDocumentIdGet<TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetDocumentApiDocumentsDocumentIdGetQueryOptions(documentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetDocumentApiDocumentsDocumentIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(documentId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentApiDocumentsDocumentIdGetQueryKey(documentId);

  const getDocumentApiDocumentsDocumentIdGet =  useGetDocumentApiDocumentsDocumentIdGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>> = ({ signal }) => getDocumentApiDocumentsDocumentIdGet(documentId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentApiDocumentsDocumentIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>>
export type GetDocumentApiDocumentsDocumentIdGetSuspenseQueryError = HTTPValidationError


export function useGetDocumentApiDocumentsDocumentIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(
 documentId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentApiDocumentsDocumentIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentApiDocumentsDocumentIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Document
 */

export function useGetDocumentApiDocumentsDocumentIdGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError = HTTPValidationError>(
 documentId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetDocumentApiDocumentsDocumentIdGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetDocumentApiDocumentsDocumentIdGetSuspenseQueryOptions(documentId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




