/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Create an organization; caller becomes Org Owner.
 * @summary Create Org
 */
export const createOrgApiOrgsPostBodyNameMax = 255;



export const CreateOrgApiOrgsPostBody = zod.object({
  "name": zod.string().min(1).max(createOrgApiOrgsPostBodyNameMax)
})

/**
 * @summary Get Admin Metrics
 */
export const GetAdminMetricsApiOrgsOrgIdAdminMetricsGetParams = zod.object({
  "org_id": zod.uuid()
})

export const GetAdminMetricsApiOrgsOrgIdAdminMetricsGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const getAdminMetricsApiOrgsOrgIdAdminMetricsGetResponseConflictResolvedCountDefault = 0;
export const getAdminMetricsApiOrgsOrgIdAdminMetricsGetResponseConflictNotAConflictCountDefault = 0;

export const GetAdminMetricsApiOrgsOrgIdAdminMetricsGetResponse = zod.object({
  "trace_count": zod.number(),
  "total_cost_usd": zod.number(),
  "average_latency_ms": zod.union([zod.number(),zod.null()]).optional(),
  "job_count": zod.number(),
  "job_pass_rate": zod.union([zod.number(),zod.null()]).optional(),
  "post_count": zod.number(),
  "package_count": zod.number(),
  "suggestion_count": zod.number(),
  "conflict_false_positive_rate": zod.union([zod.number(),zod.null()]).optional(),
  "conflict_resolved_count": zod.number().default(getAdminMetricsApiOrgsOrgIdAdminMetricsGetResponseConflictResolvedCountDefault),
  "conflict_not_a_conflict_count": zod.number().default(getAdminMetricsApiOrgsOrgIdAdminMetricsGetResponseConflictNotAConflictCountDefault)
})

