/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  AdminMetricsResponse,
  HTTPValidationError,
  OrgCreate,
  OrgResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * Create an organization; caller becomes Org Owner.
 * @summary Create Org
 */
export const useCreateOrgApiOrgsPostHook = () => {
        const createOrgApiOrgsPost = useCustomInstance<OrgResponse>();

        return useCallback((
    orgCreate: OrgCreate,
 signal?: AbortSignal
) => {
        return createOrgApiOrgsPost(
          {url: `/api/orgs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: orgCreate, signal
    },
          );
        }, [createOrgApiOrgsPost])
      }



export const useCreateOrgApiOrgsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateOrgApiOrgsPostHook>>>, TError,{data: OrgCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateOrgApiOrgsPostHook>>>, TError,{data: OrgCreate}, TContext> => {

const mutationKey = ['createOrgApiOrgsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const createOrgApiOrgsPost =  useCreateOrgApiOrgsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useCreateOrgApiOrgsPostHook>>>, {data: OrgCreate}> = (props) => {
          const {data} = props ?? {};

          return  createOrgApiOrgsPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateOrgApiOrgsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useCreateOrgApiOrgsPostHook>>>>
    export type CreateOrgApiOrgsPostMutationBody = OrgCreate
    export type CreateOrgApiOrgsPostMutationError = HTTPValidationError

    /**
 * @summary Create Org
 */
export const useCreateOrgApiOrgsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useCreateOrgApiOrgsPostHook>>>, TError,{data: OrgCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useCreateOrgApiOrgsPostHook>>>,
        TError,
        {data: OrgCreate},
        TContext
      > => {
      return useMutation(useCreateOrgApiOrgsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Admin Metrics
 */
export const useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook = () => {
        const getAdminMetricsApiOrgsOrgIdAdminMetricsGet = useCustomInstance<AdminMetricsResponse>();

        return useCallback((
    orgId: string,
 signal?: AbortSignal
) => {
        return getAdminMetricsApiOrgsOrgIdAdminMetricsGet(
          {url: `/api/orgs/${orgId}/admin/metrics`, method: 'GET', signal
    },
          );
        }, [getAdminMetricsApiOrgsOrgIdAdminMetricsGet])
      }




export const getGetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfiniteQueryKey = (orgId: string,) => {
    return [
    'infinite', `/api/orgs/${orgId}/admin/metrics`
    ] as const;
    }

export const getGetAdminMetricsApiOrgsOrgIdAdminMetricsGetQueryKey = (orgId: string,) => {
    return [
    `/api/orgs/${orgId}/admin/metrics`
    ] as const;
    }


export const useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>>, TError = HTTPValidationError>(orgId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfiniteQueryKey(orgId);

  const getAdminMetricsApiOrgsOrgIdAdminMetricsGet =  useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>> = ({ signal }) => getAdminMetricsApiOrgsOrgIdAdminMetricsGet(orgId, signal);





   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>>
export type GetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfiniteQueryError = HTTPValidationError


export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>>, TError = HTTPValidationError>(
 orgId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Admin Metrics
 */

export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetInfiniteQueryOptions(orgId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminMetricsApiOrgsOrgIdAdminMetricsGetQueryKey(orgId);

  const getAdminMetricsApiOrgsOrgIdAdminMetricsGet =  useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>> = ({ signal }) => getAdminMetricsApiOrgsOrgIdAdminMetricsGet(orgId, signal);





   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminMetricsApiOrgsOrgIdAdminMetricsGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>>
export type GetAdminMetricsApiOrgsOrgIdAdminMetricsGetQueryError = HTTPValidationError


export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGet<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(
 orgId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGet<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGet<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Admin Metrics
 */

export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGet<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetQueryOptions(orgId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(orgId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminMetricsApiOrgsOrgIdAdminMetricsGetQueryKey(orgId);

  const getAdminMetricsApiOrgsOrgIdAdminMetricsGet =  useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>> = ({ signal }) => getAdminMetricsApiOrgsOrgIdAdminMetricsGet(orgId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminMetricsApiOrgsOrgIdAdminMetricsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>>
export type GetAdminMetricsApiOrgsOrgIdAdminMetricsGetSuspenseQueryError = HTTPValidationError


export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(
 orgId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Admin Metrics
 */

export function useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError = HTTPValidationError>(
 orgId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetAdminMetricsApiOrgsOrgIdAdminMetricsGetSuspenseQueryOptions(orgId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




