/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Team Nodes
 */
export const ListTeamNodesApiTeamsTeamIdNodesGetParams = zod.object({
  "team_id": zod.uuid()
})

export const ListTeamNodesApiTeamsTeamIdNodesGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListTeamNodesApiTeamsTeamIdNodesGetResponseItem = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "org_id": zod.string(),
  "label": zod.string(),
  "node_type": zod.string(),
  "summary": zod.string(),
  "parent_id": zod.union([zod.string(),zod.null()]).optional(),
  "version": zod.number(),
  "document_id": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})
export const ListTeamNodesApiTeamsTeamIdNodesGetResponse = zod.array(ListTeamNodesApiTeamsTeamIdNodesGetResponseItem)

/**
 * @summary Get Node History
 */
export const GetNodeHistoryApiNodesNodeIdHistoryGetParams = zod.object({
  "node_id": zod.uuid()
})

export const GetNodeHistoryApiNodesNodeIdHistoryGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const GetNodeHistoryApiNodesNodeIdHistoryGetResponseItem = zod.object({
  "id": zod.string(),
  "node_id": zod.string(),
  "version": zod.number(),
  "snapshot": zod.record(zod.string(), zod.unknown()).optional(),
  "source": zod.string(),
  "created_at": zod.iso.datetime({})
})
export const GetNodeHistoryApiNodesNodeIdHistoryGetResponse = zod.array(GetNodeHistoryApiNodesNodeIdHistoryGetResponseItem)

/**
 * @summary Get Node Diff
 */
export const GetNodeDiffApiNodesNodeIdDiffGetParams = zod.object({
  "node_id": zod.uuid()
})





export const GetNodeDiffApiNodesNodeIdDiffGetQueryParams = zod.object({
  "from_version": zod.number().min(1),
  "to_version": zod.number().min(1)
})

export const GetNodeDiffApiNodesNodeIdDiffGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const GetNodeDiffApiNodesNodeIdDiffGetResponse = zod.object({
  "node_id": zod.string(),
  "from_version": zod.number(),
  "to_version": zod.number(),
  "diff": zod.string()
})

