/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  GetNodeDiffApiNodesNodeIdDiffGetParams,
  HTTPValidationError,
  NodeDiffResponse,
  NodeHistoryResponse,
  NodeResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * @summary List Team Nodes
 */
export const useListTeamNodesApiTeamsTeamIdNodesGetHook = () => {
        const listTeamNodesApiTeamsTeamIdNodesGet = useCustomInstance<NodeResponse[]>();

        return useCallback((
    teamId: string,
 signal?: AbortSignal
) => {
        return listTeamNodesApiTeamsTeamIdNodesGet(
          {url: `/api/teams/${teamId}/nodes`, method: 'GET', signal
    },
          );
        }, [listTeamNodesApiTeamsTeamIdNodesGet])
      }




export const getListTeamNodesApiTeamsTeamIdNodesGetInfiniteQueryKey = (teamId: string,) => {
    return [
    'infinite', `/api/teams/${teamId}/nodes`
    ] as const;
    }

export const getListTeamNodesApiTeamsTeamIdNodesGetQueryKey = (teamId: string,) => {
    return [
    `/api/teams/${teamId}/nodes`
    ] as const;
    }


export const useListTeamNodesApiTeamsTeamIdNodesGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamNodesApiTeamsTeamIdNodesGetInfiniteQueryKey(teamId);

  const listTeamNodesApiTeamsTeamIdNodesGet =  useListTeamNodesApiTeamsTeamIdNodesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>> = ({ signal }) => listTeamNodesApiTeamsTeamIdNodesGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamNodesApiTeamsTeamIdNodesGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>>
export type ListTeamNodesApiTeamsTeamIdNodesGetInfiniteQueryError = HTTPValidationError


export function useListTeamNodesApiTeamsTeamIdNodesGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamNodesApiTeamsTeamIdNodesGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamNodesApiTeamsTeamIdNodesGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Team Nodes
 */

export function useListTeamNodesApiTeamsTeamIdNodesGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListTeamNodesApiTeamsTeamIdNodesGetInfiniteQueryOptions(teamId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListTeamNodesApiTeamsTeamIdNodesGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamNodesApiTeamsTeamIdNodesGetQueryKey(teamId);

  const listTeamNodesApiTeamsTeamIdNodesGet =  useListTeamNodesApiTeamsTeamIdNodesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>> = ({ signal }) => listTeamNodesApiTeamsTeamIdNodesGet(teamId, signal);





   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamNodesApiTeamsTeamIdNodesGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>>
export type ListTeamNodesApiTeamsTeamIdNodesGetQueryError = HTTPValidationError


export function useListTeamNodesApiTeamsTeamIdNodesGet<TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamNodesApiTeamsTeamIdNodesGet<TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamNodesApiTeamsTeamIdNodesGet<TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Team Nodes
 */

export function useListTeamNodesApiTeamsTeamIdNodesGet<TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListTeamNodesApiTeamsTeamIdNodesGetQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useListTeamNodesApiTeamsTeamIdNodesGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamNodesApiTeamsTeamIdNodesGetQueryKey(teamId);

  const listTeamNodesApiTeamsTeamIdNodesGet =  useListTeamNodesApiTeamsTeamIdNodesGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>> = ({ signal }) => listTeamNodesApiTeamsTeamIdNodesGet(teamId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTeamNodesApiTeamsTeamIdNodesGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>>
export type ListTeamNodesApiTeamsTeamIdNodesGetSuspenseQueryError = HTTPValidationError


export function useListTeamNodesApiTeamsTeamIdNodesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamNodesApiTeamsTeamIdNodesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTeamNodesApiTeamsTeamIdNodesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Team Nodes
 */

export function useListTeamNodesApiTeamsTeamIdNodesGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError = HTTPValidationError>(
 teamId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTeamNodesApiTeamsTeamIdNodesGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useListTeamNodesApiTeamsTeamIdNodesGetSuspenseQueryOptions(teamId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Node History
 */
export const useGetNodeHistoryApiNodesNodeIdHistoryGetHook = () => {
        const getNodeHistoryApiNodesNodeIdHistoryGet = useCustomInstance<NodeHistoryResponse[]>();

        return useCallback((
    nodeId: string,
 signal?: AbortSignal
) => {
        return getNodeHistoryApiNodesNodeIdHistoryGet(
          {url: `/api/nodes/${nodeId}/history`, method: 'GET', signal
    },
          );
        }, [getNodeHistoryApiNodesNodeIdHistoryGet])
      }




export const getGetNodeHistoryApiNodesNodeIdHistoryGetInfiniteQueryKey = (nodeId: string,) => {
    return [
    'infinite', `/api/nodes/${nodeId}/history`
    ] as const;
    }

export const getGetNodeHistoryApiNodesNodeIdHistoryGetQueryKey = (nodeId: string,) => {
    return [
    `/api/nodes/${nodeId}/history`
    ] as const;
    }


export const useGetNodeHistoryApiNodesNodeIdHistoryGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>>, TError = HTTPValidationError>(nodeId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeHistoryApiNodesNodeIdHistoryGetInfiniteQueryKey(nodeId);

  const getNodeHistoryApiNodesNodeIdHistoryGet =  useGetNodeHistoryApiNodesNodeIdHistoryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>> = ({ signal }) => getNodeHistoryApiNodesNodeIdHistoryGet(nodeId, signal);





   return  { queryKey, queryFn, enabled: !!(nodeId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNodeHistoryApiNodesNodeIdHistoryGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>>
export type GetNodeHistoryApiNodesNodeIdHistoryGetInfiniteQueryError = HTTPValidationError


export function useGetNodeHistoryApiNodesNodeIdHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>>, TError = HTTPValidationError>(
 nodeId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeHistoryApiNodesNodeIdHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeHistoryApiNodesNodeIdHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Node History
 */

export function useGetNodeHistoryApiNodesNodeIdHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetNodeHistoryApiNodesNodeIdHistoryGetInfiniteQueryOptions(nodeId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetNodeHistoryApiNodesNodeIdHistoryGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(nodeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeHistoryApiNodesNodeIdHistoryGetQueryKey(nodeId);

  const getNodeHistoryApiNodesNodeIdHistoryGet =  useGetNodeHistoryApiNodesNodeIdHistoryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>> = ({ signal }) => getNodeHistoryApiNodesNodeIdHistoryGet(nodeId, signal);





   return  { queryKey, queryFn, enabled: !!(nodeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNodeHistoryApiNodesNodeIdHistoryGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>>
export type GetNodeHistoryApiNodesNodeIdHistoryGetQueryError = HTTPValidationError


export function useGetNodeHistoryApiNodesNodeIdHistoryGet<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(
 nodeId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeHistoryApiNodesNodeIdHistoryGet<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeHistoryApiNodesNodeIdHistoryGet<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Node History
 */

export function useGetNodeHistoryApiNodesNodeIdHistoryGet<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetNodeHistoryApiNodesNodeIdHistoryGetQueryOptions(nodeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetNodeHistoryApiNodesNodeIdHistoryGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(nodeId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeHistoryApiNodesNodeIdHistoryGetQueryKey(nodeId);

  const getNodeHistoryApiNodesNodeIdHistoryGet =  useGetNodeHistoryApiNodesNodeIdHistoryGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>> = ({ signal }) => getNodeHistoryApiNodesNodeIdHistoryGet(nodeId, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNodeHistoryApiNodesNodeIdHistoryGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>>
export type GetNodeHistoryApiNodesNodeIdHistoryGetSuspenseQueryError = HTTPValidationError


export function useGetNodeHistoryApiNodesNodeIdHistoryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(
 nodeId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeHistoryApiNodesNodeIdHistoryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeHistoryApiNodesNodeIdHistoryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Node History
 */

export function useGetNodeHistoryApiNodesNodeIdHistoryGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError = HTTPValidationError>(
 nodeId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeHistoryApiNodesNodeIdHistoryGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetNodeHistoryApiNodesNodeIdHistoryGetSuspenseQueryOptions(nodeId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Node Diff
 */
export const useGetNodeDiffApiNodesNodeIdDiffGetHook = () => {
        const getNodeDiffApiNodesNodeIdDiffGet = useCustomInstance<NodeDiffResponse>();

        return useCallback((
    nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams,
 signal?: AbortSignal
) => {
        return getNodeDiffApiNodesNodeIdDiffGet(
          {url: `/api/nodes/${nodeId}/diff`, method: 'GET',
        params, signal
    },
          );
        }, [getNodeDiffApiNodesNodeIdDiffGet])
      }




export const getGetNodeDiffApiNodesNodeIdDiffGetInfiniteQueryKey = (nodeId: string,
    params?: GetNodeDiffApiNodesNodeIdDiffGetParams,) => {
    return [
    'infinite', `/api/nodes/${nodeId}/diff`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetNodeDiffApiNodesNodeIdDiffGetQueryKey = (nodeId: string,
    params?: GetNodeDiffApiNodesNodeIdDiffGetParams,) => {
    return [
    `/api/nodes/${nodeId}/diff`, ...(params ? [params] : [])
    ] as const;
    }


export const useGetNodeDiffApiNodesNodeIdDiffGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>>, TError = HTTPValidationError>(nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeDiffApiNodesNodeIdDiffGetInfiniteQueryKey(nodeId,params);

  const getNodeDiffApiNodesNodeIdDiffGet =  useGetNodeDiffApiNodesNodeIdDiffGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>> = ({ signal }) => getNodeDiffApiNodesNodeIdDiffGet(nodeId,params, signal);





   return  { queryKey, queryFn, enabled: !!(nodeId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNodeDiffApiNodesNodeIdDiffGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>>
export type GetNodeDiffApiNodesNodeIdDiffGetInfiniteQueryError = HTTPValidationError


export function useGetNodeDiffApiNodesNodeIdDiffGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeDiffApiNodesNodeIdDiffGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeDiffApiNodesNodeIdDiffGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Node Diff
 */

export function useGetNodeDiffApiNodesNodeIdDiffGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetNodeDiffApiNodesNodeIdDiffGetInfiniteQueryOptions(nodeId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetNodeDiffApiNodesNodeIdDiffGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeDiffApiNodesNodeIdDiffGetQueryKey(nodeId,params);

  const getNodeDiffApiNodesNodeIdDiffGet =  useGetNodeDiffApiNodesNodeIdDiffGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>> = ({ signal }) => getNodeDiffApiNodesNodeIdDiffGet(nodeId,params, signal);





   return  { queryKey, queryFn, enabled: !!(nodeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNodeDiffApiNodesNodeIdDiffGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>>
export type GetNodeDiffApiNodesNodeIdDiffGetQueryError = HTTPValidationError


export function useGetNodeDiffApiNodesNodeIdDiffGet<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeDiffApiNodesNodeIdDiffGet<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeDiffApiNodesNodeIdDiffGet<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Node Diff
 */

export function useGetNodeDiffApiNodesNodeIdDiffGet<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetNodeDiffApiNodesNodeIdDiffGetQueryOptions(nodeId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetNodeDiffApiNodesNodeIdDiffGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNodeDiffApiNodesNodeIdDiffGetQueryKey(nodeId,params);

  const getNodeDiffApiNodesNodeIdDiffGet =  useGetNodeDiffApiNodesNodeIdDiffGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>> = ({ signal }) => getNodeDiffApiNodesNodeIdDiffGet(nodeId,params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNodeDiffApiNodesNodeIdDiffGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>>
export type GetNodeDiffApiNodesNodeIdDiffGetSuspenseQueryError = HTTPValidationError


export function useGetNodeDiffApiNodesNodeIdDiffGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeDiffApiNodesNodeIdDiffGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNodeDiffApiNodesNodeIdDiffGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Node Diff
 */

export function useGetNodeDiffApiNodesNodeIdDiffGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError = HTTPValidationError>(
 nodeId: string,
    params: GetNodeDiffApiNodesNodeIdDiffGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetNodeDiffApiNodesNodeIdDiffGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetNodeDiffApiNodesNodeIdDiffGetSuspenseQueryOptions(nodeId,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




