/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Get Profile
 */
export const GetProfileApiTeamsTeamIdProfileGetParams = zod.object({
  "team_id": zod.uuid()
})

export const GetProfileApiTeamsTeamIdProfileGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const GetProfileApiTeamsTeamIdProfileGetResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "version": zod.number(),
  "data": zod.record(zod.string(), zod.unknown()),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary Put Profile
 */
export const PutProfileApiTeamsTeamIdProfilePutParams = zod.object({
  "team_id": zod.uuid()
})

export const PutProfileApiTeamsTeamIdProfilePutHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const PutProfileApiTeamsTeamIdProfilePutBody = zod.object({
  "data": zod.record(zod.string(), zod.unknown()).optional()
})

export const PutProfileApiTeamsTeamIdProfilePutResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "version": zod.number(),
  "data": zod.record(zod.string(), zod.unknown()),
  "created_at": zod.iso.datetime({})
})

/**
 * @summary Draft Profile From Document
 */
export const DraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostParams = zod.object({
  "team_id": zod.uuid()
})

export const DraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const DraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostBody = zod.object({
  "document_id": zod.uuid()
})

export const DraftProfileFromDocumentApiTeamsTeamIdProfileDraftFromDocumentPostResponse = zod.object({
  "document_id": zod.string(),
  "data": zod.object({
  "purpose": zod.string(),
  "audiences": zod.array(zod.string()).optional(),
  "tone": zod.string(),
  "communication_preferences": zod.array(zod.string()).optional(),
  "known_terms": zod.array(zod.string()).optional()
}),
  "generated_by": zod.enum(['mistral', 'deterministic_stub'])
})

