/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Create Team
 */
export const CreateTeamApiOrgsOrgIdTeamsPostParams = zod.object({
  "org_id": zod.uuid()
})

export const CreateTeamApiOrgsOrgIdTeamsPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const createTeamApiOrgsOrgIdTeamsPostBodyNameMax = 255;



export const CreateTeamApiOrgsOrgIdTeamsPostBody = zod.object({
  "name": zod.string().min(1).max(createTeamApiOrgsOrgIdTeamsPostBodyNameMax)
})

/**
 * @summary Create Invite
 */
export const CreateInviteApiTeamsTeamIdInvitesPostParams = zod.object({
  "team_id": zod.uuid()
})

export const CreateInviteApiTeamsTeamIdInvitesPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const createInviteApiTeamsTeamIdInvitesPostBodyEmailOneMin = 3;
export const createInviteApiTeamsTeamIdInvitesPostBodyEmailOneMax = 255;

export const createInviteApiTeamsTeamIdInvitesPostBodyUsernameOneMin = 3;
export const createInviteApiTeamsTeamIdInvitesPostBodyUsernameOneMax = 32;

export const createInviteApiTeamsTeamIdInvitesPostBodyRoleDefault = `member`;

export const CreateInviteApiTeamsTeamIdInvitesPostBody = zod.object({
  "email": zod.union([zod.string().min(createInviteApiTeamsTeamIdInvitesPostBodyEmailOneMin).max(createInviteApiTeamsTeamIdInvitesPostBodyEmailOneMax),zod.null()]).optional(),
  "username": zod.union([zod.string().min(createInviteApiTeamsTeamIdInvitesPostBodyUsernameOneMin).max(createInviteApiTeamsTeamIdInvitesPostBodyUsernameOneMax),zod.null()]).optional(),
  "role": zod.string().default(createInviteApiTeamsTeamIdInvitesPostBodyRoleDefault)
}).describe('Invite by email and\/or username (at least one required).')

/**
 * @summary Accept Invite
 */
export const acceptInviteApiInvitesAcceptPostBodyTokenMin = 8;
export const acceptInviteApiInvitesAcceptPostBodyTokenMax = 128;



export const AcceptInviteApiInvitesAcceptPostBody = zod.object({
  "token": zod.string().min(acceptInviteApiInvitesAcceptPostBodyTokenMin).max(acceptInviteApiInvitesAcceptPostBodyTokenMax)
})

export const acceptInviteApiInvitesAcceptPostResponseAddedImmediatelyDefault = false;

export const AcceptInviteApiInvitesAcceptPostResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "email": zod.string(),
  "role": zod.string(),
  "token": zod.string(),
  "created_at": zod.iso.datetime({}),
  "added_immediately": zod.boolean().default(acceptInviteApiInvitesAcceptPostResponseAddedImmediatelyDefault)
})

/**
 * @summary Remove Member
 */
export const RemoveMemberApiTeamsTeamIdMembersUserIdRemovePostParams = zod.object({
  "team_id": zod.uuid(),
  "user_id": zod.uuid()
})

export const RemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary List Members
 */
export const ListMembersApiTeamsTeamIdMembersGetParams = zod.object({
  "team_id": zod.uuid()
})

export const ListMembersApiTeamsTeamIdMembersGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListMembersApiTeamsTeamIdMembersGetResponseItem = zod.record(zod.string(), zod.string())
export const ListMembersApiTeamsTeamIdMembersGetResponse = zod.array(ListMembersApiTeamsTeamIdMembersGetResponseItem)

