/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Create Team
 */
export const CreateTeamApiOrgsOrgIdTeamsPostParams = zod.object({
  "org_id": zod.uuid()
})

export const CreateTeamApiOrgsOrgIdTeamsPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const createTeamApiOrgsOrgIdTeamsPostBodyNameMax = 255;



export const CreateTeamApiOrgsOrgIdTeamsPostBody = zod.object({
  "name": zod.string().min(1).max(createTeamApiOrgsOrgIdTeamsPostBodyNameMax)
})

/**
 * @summary Create Invite
 */
export const CreateInviteApiTeamsTeamIdInvitesPostParams = zod.object({
  "team_id": zod.uuid()
})

export const CreateInviteApiTeamsTeamIdInvitesPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const createInviteApiTeamsTeamIdInvitesPostBodyEmailMin = 3;
export const createInviteApiTeamsTeamIdInvitesPostBodyEmailMax = 255;

export const createInviteApiTeamsTeamIdInvitesPostBodyRoleDefault = `member`;

export const CreateInviteApiTeamsTeamIdInvitesPostBody = zod.object({
  "email": zod.string().min(createInviteApiTeamsTeamIdInvitesPostBodyEmailMin).max(createInviteApiTeamsTeamIdInvitesPostBodyEmailMax),
  "role": zod.string().default(createInviteApiTeamsTeamIdInvitesPostBodyRoleDefault)
})

/**
 * @summary Remove Member
 */
export const RemoveMemberApiTeamsTeamIdMembersUserIdRemovePostParams = zod.object({
  "team_id": zod.uuid(),
  "user_id": zod.uuid()
})

export const RemoveMemberApiTeamsTeamIdMembersUserIdRemovePostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary List Members
 */
export const ListMembersApiTeamsTeamIdMembersGetParams = zod.object({
  "team_id": zod.uuid()
})

export const ListMembersApiTeamsTeamIdMembersGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListMembersApiTeamsTeamIdMembersGetResponseItem = zod.record(zod.string(), zod.string())
export const ListMembersApiTeamsTeamIdMembersGetResponse = zod.array(ListMembersApiTeamsTeamIdMembersGetResponseItem)

