/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Upload Document
 */
export const UploadDocumentApiTeamsTeamIdDocumentsPostParams = zod.object({
  "team_id": zod.uuid()
})

export const UploadDocumentApiTeamsTeamIdDocumentsPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const UploadDocumentApiTeamsTeamIdDocumentsPostBody = zod.object({
  "file": zod.instanceof(File)
})

/**
 * @summary Paste Document
 */
export const PasteDocumentApiTeamsTeamIdDocumentsPastePostParams = zod.object({
  "team_id": zod.uuid()
})

export const PasteDocumentApiTeamsTeamIdDocumentsPastePostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})


export const pasteDocumentApiTeamsTeamIdDocumentsPastePostBodyFilenameDefault = `paste.txt`;
export const pasteDocumentApiTeamsTeamIdDocumentsPastePostBodyFilenameMax = 255;



export const PasteDocumentApiTeamsTeamIdDocumentsPastePostBody = zod.object({
  "text": zod.string().min(1),
  "filename": zod.string().min(1).max(pasteDocumentApiTeamsTeamIdDocumentsPastePostBodyFilenameMax).default(pasteDocumentApiTeamsTeamIdDocumentsPastePostBodyFilenameDefault)
})

/**
 * @summary Get Document
 */
export const GetDocumentApiDocumentsDocumentIdGetParams = zod.object({
  "document_id": zod.uuid()
})

export const GetDocumentApiDocumentsDocumentIdGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const GetDocumentApiDocumentsDocumentIdGetResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "org_id": zod.string(),
  "filename": zod.string(),
  "status": zod.string(),
  "storage_uri": zod.union([zod.string(),zod.null()]).optional(),
  "job_id": zod.union([zod.string(),zod.null()]).optional(),
  "created_at": zod.iso.datetime({})
})

