/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Glossary
 */
export const ListGlossaryApiTeamsTeamIdGlossaryGetParams = zod.object({
  "team_id": zod.uuid()
})

export const ListGlossaryApiTeamsTeamIdGlossaryGetHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const ListGlossaryApiTeamsTeamIdGlossaryGetResponseItem = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "term": zod.string(),
  "definition": zod.string(),
  "kind": zod.enum(['known', 'must_explain']),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})
export const ListGlossaryApiTeamsTeamIdGlossaryGetResponse = zod.array(ListGlossaryApiTeamsTeamIdGlossaryGetResponseItem)

/**
 * @summary Create Glossary Term
 */
export const CreateGlossaryTermApiTeamsTeamIdGlossaryPostParams = zod.object({
  "team_id": zod.uuid()
})

export const CreateGlossaryTermApiTeamsTeamIdGlossaryPostHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const createGlossaryTermApiTeamsTeamIdGlossaryPostBodyTermMax = 255;


export const createGlossaryTermApiTeamsTeamIdGlossaryPostBodyKindDefault = `known`;

export const CreateGlossaryTermApiTeamsTeamIdGlossaryPostBody = zod.object({
  "term": zod.string().min(1).max(createGlossaryTermApiTeamsTeamIdGlossaryPostBodyTermMax),
  "definition": zod.string().min(1),
  "kind": zod.enum(['known', 'must_explain']).default(createGlossaryTermApiTeamsTeamIdGlossaryPostBodyKindDefault)
})

/**
 * @summary Update Glossary Term
 */
export const UpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchParams = zod.object({
  "team_id": zod.uuid(),
  "term_id": zod.uuid()
})

export const UpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

export const updateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchBodyTermOneMax = 255;




export const UpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchBody = zod.object({
  "term": zod.union([zod.string().min(1).max(updateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchBodyTermOneMax),zod.null()]).optional(),
  "definition": zod.union([zod.string().min(1),zod.null()]).optional(),
  "kind": zod.union([zod.enum(['known', 'must_explain']),zod.null()]).optional()
})

export const UpdateGlossaryTermApiTeamsTeamIdGlossaryTermIdPatchResponse = zod.object({
  "id": zod.string(),
  "team_id": zod.string(),
  "term": zod.string(),
  "definition": zod.string(),
  "kind": zod.enum(['known', 'must_explain']),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
})

/**
 * @summary Delete Glossary Term
 */
export const DeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteParams = zod.object({
  "team_id": zod.uuid(),
  "term_id": zod.uuid()
})

export const DeleteGlossaryTermApiTeamsTeamIdGlossaryTermIdDeleteHeader = zod.object({
  "X-Org-Id": zod.union([zod.string(),zod.null()]).optional(),
  "X-Team-Id": zod.union([zod.string(),zod.null()]).optional()
})

